# Generated by Django 6.1 on 2026-09-01 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0001_initial'),
        ('core', '0004_companysetting_advance_loan_sms_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('api_bearer_token', models.CharField(default='awaj_xxxxxxxxxxxxxxxxxxxxxxxx', max_length=255)),
                ('caller_sender_id', models.CharField(blank=True, default='+8809612000000', max_length=50)),
                ('voice_file_name', models.CharField(blank=True, default='my_reminder_voice', max_length=100)),
                ('enable_expiry_reminder', models.BooleanField(default=True)),
                ('call_when', models.CharField(default='On Expiry Date', max_length=50)),
                ('call_time', models.CharField(default='10:00 AM', max_length=20)),
                ('retry_unanswered', models.BooleanField(default=False)),
                ('max_attempts', models.CharField(default='1 Attempt (No Retry)', max_length=50)),
                ('retry_delay', models.CharField(default='1 Hour', max_length=50)),
                ('safe_hours_start', models.CharField(default='09:00 AM', max_length=20)),
                ('safe_hours_end', models.CharField(default='08:00 PM', max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calls_today', models.PositiveIntegerField(default=0)),
                ('answered_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_setting', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voice_name', models.CharField(max_length=100)),
                ('audio_file_url', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending Review'), ('Rejected', 'Rejected')], default='Approved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_templates', to='core.tenant')),
            ],
        ),
    ]
