# Generated by Django 6.1 on 2026-09-26 09:47

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_voicesetting_voicetemplate'),
        ('core', '0012_apiapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPBXMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='PBX extension (e.g. 101)', max_length=20)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_mapping', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_agent_mappings', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MikoPBXConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('pbx_url', models.URLField(blank=True, help_text='MikoPBX HTTPS URL', null=True)),
                ('pbx_did', models.CharField(blank=True, help_text="Tenant's assigned DID", max_length=50)),
                ('api_key', apps.core.fields.EncryptedCharField(blank=True, help_text='Read-only MikoPBX API key with cdr:read', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mikopbx_config', to='core.tenant')),
            ],
        ),
    ]
