# Generated by Django 6.1 on 2026-09-26 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_agentpbxmapping_mikopbxconfig'),
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        ('customers', '0006_customer_cpe_admin_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-call_start_time', '-created_at']},
        ),
        migrations.AddField(
            model_name='calllog',
            name='api_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ip_phone_extension',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calllog',
            name='is_sip_client',
            field=models.BooleanField(default=False, help_text='True when the call was placed via a WebSIP browser softphone.'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='calllog',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('Inbound', 'Inbound Support'), ('Outbound', 'Outbound Follow-up'), ('Broadcast', 'Voice Broadcast / Reminder'), ('Manual', 'Manual Click-to-Call'), ('WebSIP', 'WebSIP Browser Softphone')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('Answered', 'Answered / Completed'), ('Missed', 'Missed Call'), ('Busy', 'Line Busy'), ('Failed', 'Failed'), ('WebSIP', 'Browser WebSIP'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Call Back Later', 'Call Back Later'), ('Complaint Solved', 'Complaint Solved')], default='Answered', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerFollowup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('followup_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Billing', 'Billing'), ('Complaint', 'Complaint'), ('Sales', 'Sales'), ('Technical', 'Technical'), ('Other', 'Other')], default='Billing', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Call Back Later', 'Call Back Later'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='callcenter.calllog')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_followups', to='core.tenant')),
            ],
            options={
                'ordering': ['-followup_date'],
            },
        ),
        migrations.CreateModel(
            name='IPPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_number', models.CharField(max_length=50)),
                ('password_enc', models.CharField(blank=True, default='', max_length=512)),
                ('sip_server', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5060)),
                ('wss_uri', models.CharField(blank=True, default='', max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_phone_numbers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_phone_numbers', to='core.tenant')),
            ],
            options={
                'ordering': ['is_main', 'ip_number'],
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Due bill reminder', 'Due bill reminder'), ('Expiry notice', 'Expiry notice'), ('Welcome', 'Welcome message'), ('Complaint update', 'Complaint update'), ('Custom', 'Custom broadcast')], default='Due bill reminder', max_length=40)),
                ('message_text', models.TextField(help_text='Transcript; supports [NAME] [ID] [AMOUNT] [DATE] [PACKAGE].')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_templates/')),
                ('language', models.CharField(default='Bangla', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, help_text='Owning staff (legacy PHP staff_id column).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_templates_v2', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('target', models.CharField(choices=[('expired', 'Expired packages'), ('due', 'Customers with positive due'), ('all', 'All active customers')], default='expired', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='callcenter.remindertemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_campaigns', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPPhoneConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver', models.CharField(choices=[('flemsoft', 'Flemsoft Voice API'), ('generic_rest', 'Generic REST')], default='generic_rest', max_length=30)),
                ('base_url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password_token_enc', models.CharField(blank=True, default='', max_length=512)),
                ('caller_id', models.CharField(blank=True, default='', max_length=30)),
                ('extension', models.CharField(blank=True, default='', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('test_mode', models.BooleanField(default=False, help_text='When true, click-to-call logs without dialling. Mirrors PHP test_mode.')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_phone_configs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_phone_configs', to='core.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'staff'), name='ip_phone_config_tenant_staff_uniq')],
            },
        ),
        migrations.CreateModel(
            name='VoiceCampaignItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
                ('body_text', models.TextField()),
                ('audio_file', models.CharField(blank=True, default='', help_text='Resolved audio path (or empty for TTS).', max_length=255)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='callcenter.voicecampaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='vcamp_status_idx')],
            },
        ),
    ]
