# Generated by Django 6.1 on 2026-09-02 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_advancesalary_leaverequest_payrollrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalary',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
