<?php
// Auto-generated by Installer for Tenant: arlink
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_arlink');
define('DB_USER', 'shebafi_arlink');
define('DB_PASS', 'Mother466@');
?>