<?php
// Auto-generated by Installer for Tenant: at
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_anwartele');
define('DB_USER', 'shebafi_anwartele');
define('DB_PASS', 'anwartele123@');
?>