<?php
// Auto-generated by Installer for Tenant: beeonline
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_beeonline');
define('DB_USER', 'shebafi_beeonline');
define('DB_PASS', 'Mother519466@');
?>