<?php
// Auto-generated by Installer for Tenant: billing
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_ripa1');
define('DB_USER', 'shebafi_ripa1');
define('DB_PASS', 'ripaonline1');
?>