<?php
// Auto-generated by Installer for Tenant: bntc
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_bntc');
define('DB_USER', 'shebafi_bntc');
define('DB_PASS', 'Mother519466@');
?>