<?php
// Auto-generated by Installer for Tenant: jackint
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_jackint');
define('DB_USER', 'shebafi_jackint');
define('DB_PASS', 'Mother466@');
?>