<?php
// Auto-generated by Installer for Tenant: nexus
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_nexus');
define('DB_USER', 'shebafi_nexus');
define('DB_PASS', 'Mother466@');
?>