<?php
// Auto-generated by Installer for Tenant: optihub
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_optihub');
define('DB_USER', 'shebafi_optihub');
define('DB_PASS', 'Mother466@');
?>