<?php
// Auto-generated by Installer for Tenant: paglapir
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_paglapir');
define('DB_USER', 'shebafi_paglapir');
define('DB_PASS', 'Mother466@');
?>