<?php
// Auto-generated by Installer for Tenant: rcn
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_relationcable');
define('DB_USER', 'shebafi_relationcable');
define('DB_PASS', 'relationcable123@');
?>