<?php
// Auto-generated by Installer for Tenant: ripamac
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_ripamac');
define('DB_USER', 'shebafi_ripamac');
define('DB_PASS', 'Mother519466@');
?>