<?php
// Auto-generated by Installer for Tenant: smooth
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_smooth');
define('DB_USER', 'shebafi_smooth');
define('DB_PASS', 'Mother466@');
?>