<?php
// Auto-generated by Installer for Tenant: sns
define('DB_HOST', 'localhost');
define('DB_NAME', 'shebafi_minhaj');
define('DB_USER', 'shebafi_minhaj');
define('DB_PASS', 'Mother466@');
?>