import type { ComponentType } from 'react';
import type { PortalType } from './types';
import { PERMISSIONS } from './permissions';
import {
    Activity,
    BarChart01,
    BookOpen01,
    Building07,
    CreditCard01,
    Database01,
    File06,
    Globe01,
    LayersThree01,
    Package,
    Receipt,
    Server01,
    Settings01,
    Signal01,
    Ticket01,
    Users01,
    Zap,
    CpuChip01,
} from '@untitledui/icons';

export interface ModuleItem {
    id: string;
    label: string;
    name?: string; // alias for label
    path: string;
    routes?: string[];
    icon: ComponentType<{ className?: string }>;
    portals: PortalType[];
    allowedPortals?: PortalType[]; // alias for portals
    badge?: string;
    roles?: string[];
    permissions?: string[];
    featureFlag?: string;
    visibility?: 'always' | 'permission_gated' | 'feature_gated';
    description?: string;
}

export const MODULE_REGISTRY: ModuleItem[] = [
    // ══════════════════════════════════════════════════════════════════════════
    // SUPER ADMIN MODULES (Global Control Plane: admin.example.xyz)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'platform-dashboard',
        label: 'Platform Overview',
        name: 'Platform Overview',
        path: '/',
        routes: ['/', '/dashboard'],
        icon: Activity,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Global SaaS metrics, active tenants, MRR and health telemetry',
    },
    {
        id: 'platform-isps',
        label: 'ISP Tenants',
        name: 'ISP Tenants',
        path: '/tenants',
        routes: ['/tenants', '/isps'],
        icon: Building07,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.TENANT_PROVISION],
        description: 'Provision, suspend, quota and manage all ISP organizations',
    },
    {
        id: 'platform-plans',
        label: 'Platform Plans',
        name: 'Platform Plans',
        path: '/packages',
        routes: ['/packages', '/plans'],
        icon: Package,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'SaaS subscription packages, pricing tiers and quotas',
    },
    {
        id: 'platform-subscriptions',
        label: 'Subscriptions',
        name: 'Subscriptions',
        path: '/subscriptions',
        routes: ['/subscriptions'],
        icon: CreditCard01,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Active ISP licenses, renewal cycles, and statuses',
    },
    {
        id: 'platform-billing',
        label: 'Platform Billing',
        name: 'Platform Billing',
        path: '/payments',
        routes: ['/payments', '/billing'],
        icon: Receipt,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Inbound SaaS subscription revenues and payment ledger',
    },
    {
        id: 'platform-users',
        label: 'Platform Staff',
        name: 'Platform Staff',
        path: '/employees',
        routes: ['/employees', '/users'],
        icon: Users01,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Global control plane operators, admins, and support agents',
    },
    {
        id: 'platform-onboarding',
        label: 'Onboarding Queue',
        name: 'Onboarding Queue',
        path: '/onboarding',
        routes: ['/onboarding'],
        icon: BookOpen01,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.TENANT_PROVISION],
        description: 'Triage and approve incoming ISP registration requests',
    },
    {
        id: 'platform-domains',
        label: 'Custom Domains',
        name: 'Custom Domains',
        path: '/domains',
        routes: ['/domains', '/settings'],
        icon: Globe01,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'DNS challenge verification, SSL certificates, and routing',
    },
    {
        id: 'platform-feature-matrix',
        label: 'Feature Matrix',
        name: 'Feature Matrix',
        path: '/feature-matrix',
        routes: ['/feature-matrix'],
        icon: LayersThree01,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Global and per-tenant module flag controls',
    },
    {
        id: 'platform-backups',
        label: 'Disaster Recovery',
        name: 'Disaster Recovery',
        path: '/backups',
        routes: ['/backups'],
        icon: Database01,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Automated database snapshots and storage snapshots',
    },
    {
        id: 'platform-audit-logs',
        label: 'Audit Trail',
        name: 'Audit Trail',
        path: '/audit-logs',
        routes: ['/audit-logs'],
        icon: File06,
        portals: ['SUPER_ADMIN'],
        allowedPortals: ['SUPER_ADMIN'],
        permissions: [PERMISSIONS.PLATFORM_MANAGE],
        description: 'Immutable security log of platform-level events',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // ISP ADMIN MODULES (Operations: app.example.xyz)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'isp-dashboard',
        label: 'Operations Cockpit',
        name: 'Operations Cockpit',
        path: '/',
        routes: ['/', '/dashboard'],
        icon: BarChart01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        description: 'Live bandwidth, active PPPoE sessions, revenue summary',
    },
    {
        id: 'isp-customers',
        label: 'Subscribers',
        name: 'Subscribers',
        path: '/customers',
        routes: ['/customers'],
        icon: Users01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.CUSTOMER_READ],
        featureFlag: 'customers.active',
        description: 'Manage active, expired, and lead subscriber accounts',
    },
    {
        id: 'isp-billing',
        label: 'Billing & Invoices',
        name: 'Billing & Invoices',
        path: '/billing',
        routes: ['/billing'],
        icon: Receipt,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.BILLING_READ],
        featureFlag: 'billing.invoices',
        description: 'Monthly invoicing, bKash/Nagad collections, ledger accounts',
    },
    {
        id: 'isp-subscriptions',
        label: 'ISP Subscriptions',
        name: 'ISP Subscriptions',
        path: '/subscriptions',
        routes: ['/subscriptions'],
        icon: CreditCard01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.SUBSCRIPTION_READ],
        description: 'Subscriber package subscriptions and expiry renewals',
    },
    {
        id: 'isp-mikrotik',
        label: 'MikroTik Routers',
        name: 'MikroTik Routers',
        path: '/mikrotik',
        routes: ['/mikrotik', '/network'],
        icon: Server01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.MIKROTIK_READ],
        featureFlag: 'network.mikrotik',
        description: 'RouterOS sync, API connections, queues, and interface telemetry',
    },
    {
        id: 'isp-pppoe',
        label: 'PPPoE Sessions',
        name: 'PPPoE Sessions',
        path: '/pppoe',
        routes: ['/pppoe'],
        icon: CpuChip01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.PPPOE_READ],
        featureFlag: 'network.pppoe',
        description: 'Live active PPPoE sessions, secret credentials, pool bindings',
    },
    {
        id: 'isp-olt',
        label: 'OLT Management',
        name: 'OLT Management',
        path: '/olt',
        routes: ['/olt'],
        icon: LayersThree01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.OLT_READ],
        featureFlag: 'network.olt',
        description: 'Optical Line Terminals, PON ports, and optical power levels',
    },
    {
        id: 'isp-onu',
        label: 'ONU Inventory',
        name: 'ONU Inventory',
        path: '/onu',
        routes: ['/onu'],
        icon: Signal01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.ONU_READ],
        featureFlag: 'network.onu',
        description: 'Optical Network Units, MAC addresses, and fiber link status',
    },
    {
        id: 'isp-tickets',
        label: 'Support Tickets',
        name: 'Support Tickets',
        path: '/tickets',
        routes: ['/tickets'],
        icon: Ticket01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.TICKET_READ],
        featureFlag: 'support.tickets',
        description: 'NOC incidents, line cuts, and subscriber complaint tracking',
    },
    {
        id: 'isp-reports',
        label: 'Reports & Analytics',
        name: 'Reports & Analytics',
        path: '/reports',
        routes: ['/reports'],
        icon: File06,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.REPORT_READ],
        featureFlag: 'analytics.dashboard',
        description: 'Financial collections, churn analytics, and bandwidth logs',
    },
    {
        id: 'isp-settings',
        label: 'ISP Settings',
        name: 'ISP Settings',
        path: '/settings',
        routes: ['/settings'],
        icon: Settings01,
        portals: ['ISP_ADMIN'],
        allowedPortals: ['ISP_ADMIN'],
        permissions: [PERMISSIONS.SETTINGS_READ],
        description: 'Company profile, MFS gateways, SMS templates, branding',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // TENANT APPLICATION MODULES ({tenant}.example.com)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'tenant-dashboard',
        label: 'Overview',
        name: 'Overview',
        path: '/',
        routes: ['/', '/dashboard'],
        icon: Globe01,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        description: 'Connection status, current bandwidth, and billing summary',
    },
    {
        id: 'tenant-customers',
        label: 'Account Profile',
        name: 'Account Profile',
        path: '/customers',
        routes: ['/customers'],
        icon: Users01,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        description: 'Personal details, installation address, and credentials',
    },
    {
        id: 'tenant-billing',
        label: 'Bills & Payments',
        name: 'Bills & Payments',
        path: '/billing',
        routes: ['/billing', '/invoices'],
        icon: Receipt,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        permissions: [PERMISSIONS.BILLING_READ],
        description: 'View unpaid invoices, payment history, and instant checkout',
    },
    {
        id: 'tenant-subscriptions',
        label: 'My Internet Plan',
        name: 'My Internet Plan',
        path: '/subscriptions',
        routes: ['/subscriptions', '/recharge'],
        icon: Zap,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        permissions: [PERMISSIONS.SUBSCRIPTION_READ],
        description: 'Current speed plan, booster recharge, and upgrade options',
    },
    {
        id: 'tenant-tickets',
        label: 'Helpdesk & Support',
        name: 'Helpdesk & Support',
        path: '/tickets',
        routes: ['/tickets', '/support'],
        icon: Ticket01,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        permissions: [PERMISSIONS.TICKET_READ],
        description: 'Create disruption tickets and chat with ISP support staff',
    },
    {
        id: 'tenant-reports',
        label: 'Usage Analytics',
        name: 'Usage Analytics',
        path: '/reports',
        routes: ['/reports', '/usage'],
        icon: Signal01,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        permissions: [PERMISSIONS.REPORT_READ],
        description: 'Daily bandwidth graphs, upload/download stats, and sessions',
    },
    {
        id: 'tenant-settings',
        label: 'Preferences',
        name: 'Preferences',
        path: '/settings',
        routes: ['/settings'],
        icon: Settings01,
        portals: ['TENANT'],
        allowedPortals: ['TENANT'],
        description: 'Password change, notifications, and language preferences',
    },
];

export function getModulesForPortal(portal: PortalType): ModuleItem[] {
    return MODULE_REGISTRY.filter((m) => m.portals.includes(portal));
}
