# Generated by Django 6.1 on 2026-09-01 13:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('hmac_secret', models.CharField(default=uuid.uuid4, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Sheba Fi Internet', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Ultra Fast Fiber Broadband', max_length=255)),
                ('currency_symbol', models.CharField(default='৳', max_length=10)),
                ('currency_code', models.CharField(default='BDT', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('customer_id_prefix', models.CharField(default='CUST', max_length=10)),
                ('support_phone', models.CharField(blank=True, default='+8801700000000', max_length=50)),
                ('support_email', models.EmailField(blank=True, default='support@shebafi.com', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('sms_sender_id', models.CharField(blank=True, default='SHEBA', max_length=50)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('sms_gateway_url', models.CharField(blank=True, max_length=255)),
                ('auto_lock_on_expiry', models.BooleanField(default=True)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_username', models.CharField(default='system', max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TenantApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='core.tenant')),
            ],
        ),
    ]
