# Generated by Django 6.1 on 2026-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='accent_color',
            field=models.CharField(choices=[('indigo', 'Electric Indigo'), ('emerald', 'Cyber Emerald'), ('violet', 'Ultra Violet'), ('cyan', 'Neon Cyan'), ('amber', 'Golden Amber'), ('rose', 'Vibrant Rose')], default='indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='auto_generate_monthly_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='billing_footer_note',
            field=models.TextField(blank=True, default='Thank you for choosing Sheba Fi. Pay online via bKash or Nagad.'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='default_dns_primary',
            field=models.GenericIPAddressField(default='8.8.8.8'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='default_dns_secondary',
            field=models.GenericIPAddressField(default='1.1.1.1'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='favicon_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='live_traffic_interval_sec',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='mikrotik_auto_kick_on_expire',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='mikrotik_default_port',
            field=models.PositiveIntegerField(default=8728),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='mikrotik_timeout_sec',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='promise_max_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='send_sms_on_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='send_sms_on_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='sms_provider',
            field=models.CharField(choices=[('Greenweb', 'Greenweb Bangladesh API'), ('BulkSMSBD', 'BulkSMS BD HTTP Gateway'), ('Onnorokom', 'Onnorokom SMS Gateway'), ('Twilio', 'Twilio Cloud SMS'), ('Generic', 'Generic HTTP POST / Modem Webhook')], default='Greenweb', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='sms_reminder_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='tax_number',
            field=models.CharField(blank=True, default='BIN-123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Dark Glassmorphic (Default)'), ('light', 'Clean Light Mode'), ('system', 'System Default'), ('midnight', 'Midnight Deep Blue'), ('cyberpunk', 'Cyber Neon')], default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='website',
            field=models.URLField(blank=True, default='https://shebafi.net'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='address',
            field=models.TextField(blank=True, default='Level 6, Sheba Tower, Road 27, Dhanmondi, Dhaka 1209'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='company_name',
            field=models.CharField(default='Sheba Fi Internet & Network Technologies', max_length=200),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='customer_id_prefix',
            field=models.CharField(default='SHB-', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='invoice_prefix',
            field=models.CharField(default='SHB-INV-', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='sms_api_key',
            field=models.CharField(blank=True, default='gw_live_sample_key_987654', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='sms_gateway_url',
            field=models.CharField(blank=True, default='https://api.sms.net/v1/send', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='sms_sender_id',
            field=models.CharField(blank=True, default='SHEBAFI', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_email',
            field=models.EmailField(blank=True, default='support@shebafi.net', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_phone',
            field=models.CharField(blank=True, default='+8809612000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='tagline',
            field=models.CharField(blank=True, default='Ultra Fast Optical Fiber Broadband', max_length=255),
        ),
    ]
