# Generated by Django 6.1 on 2026-09-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companysetting_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='admin_expire_time',
            field=models.CharField(default='23:59', help_text='Time of day when direct active clients disabling executed', max_length=20),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='client_date_of_birth',
            field=models.DateField(blank=True, default='2003-01-01', null=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='client_name',
            field=models.CharField(blank=True, default='fardin', help_text='SaaS Client / Owner Name', max_length=150),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='payment_tutorial_video',
            field=models.URLField(blank=True, default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='recharge_discount_enabled',
            field=models.BooleanField(default=True, help_text='Enable discount fields for Manual/Bulk Recharge'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='show_reseller_profile_speed',
            field=models.BooleanField(default=True, help_text='Show Profile / Speed in Reseller My Rates Panel'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='undo_recharge_deduct_hours',
            field=models.PositiveIntegerField(default=2, help_text='Hours before 1 day cost deduction on recharge undo'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='address',
            field=models.TextField(blank=True, default='Your ISP Corporate Office Address'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='company_name',
            field=models.CharField(default='ISP Billing', max_length=200),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_email',
            field=models.EmailField(blank=True, default='billing@isp.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_phone',
            field=models.CharField(blank=True, default='+880 1234-567890', max_length=50),
        ),
    ]
