# Generated by Django 6.1 on 2026-09-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companysetting_admin_expire_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='advance_loan_sms_template',
            field=models.TextField(default='Dear [NAME], [DAYS] days credit added to ID [ID].'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='expiry_reminder_template',
            field=models.TextField(default='Dear [NAME], your service ID [ID] expires today.'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='expiry_reminder_time',
            field=models.CharField(default='12:00 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='payment_sms_template',
            field=models.TextField(default='Dear [NAME], we have received [AMOUNT]৳ for ID [ID].'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='reminder_27d_template',
            field=models.TextField(default='Dear [NAME], your bill ID [ID] is due in 3 days.'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='reminder_27d_time',
            field=models.CharField(default='12:00 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='welcome_sms_template',
            field=models.TextField(default='Welcome [NAME]! Your [ID] is active. Password: [PASS].'),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='sms_gateway_url',
            field=models.CharField(blank=True, default='https://api.provider.com/send?key={KEY}&sender={SENDER}&msg={MSG}&to={NUMBER}', help_text='Use placeholders: {KEY}, {SENDER}, {MSG}, {NUMBER}', max_length=500),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='sms_provider',
            field=models.CharField(choices=[('Custom URL Gateway', 'Custom URL Gateway'), ('Greenweb', 'Greenweb Bangladesh API'), ('BulkSMSBD', 'BulkSMS BD HTTP Gateway'), ('Onnorokom', 'Onnorokom SMS Gateway'), ('Twilio', 'Twilio Cloud SMS')], default='Custom URL Gateway', max_length=50),
        ),
    ]
