# Generated by Django 6.1 on 2026-09-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysetting_advance_loan_sms_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at']},
        ),
    ]
