# Generated by Django 6.1 on 2026-09-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tenant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('domain_type', models.CharField(choices=[('primary', 'Primary'), ('alias', 'Alias'), ('api', 'API Subdomain'), ('portal', 'Customer Portal'), ('control', 'Control Plane')], default='primary', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='after',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='audit_tenant_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'module', 'action'], name='audit_tenant_module_idx'),
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_domains', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['hostname', 'is_active'], name='domain_hostname_active_idx'),
        ),
    ]
