# Generated by Django 6.1 on 2026-09-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenantdomain_auditlog_after_auditlog_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_routers',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_subscribers',
            field=models.PositiveIntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter ISP (Up to 500 Subscribers)'), ('Growth', 'Growth ISP (Up to 2,500 Subscribers)'), ('Enterprise', 'Enterprise ISP (Unlimited Subscribers)')], default='Growth', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
