# Generated by Django 6.1 on 2026-09-07 11:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_max_routers_tenant_max_subscribers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=150000.0, max_digits=10)),
                ('max_subscribers', models.PositiveIntegerField(default=2500)),
                ('max_routers', models.PositiveIntegerField(default=10)),
                ('max_custom_domains', models.PositiveIntegerField(default=3)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True, help_text='Pause or resume this package for new subscriptions')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='TenantOnboardingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=150)),
                ('requested_slug', models.SlugField(max_length=100)),
                ('requested_domain', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('requested_plan', models.CharField(default='Growth', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Deployed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_name', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('backup_type', models.CharField(choices=[('full_database', 'Full Database Snapshot'), ('tenant_data', 'Single-Tenant JSON Export'), ('system_snapshot', 'Core System State')], default='full_database', max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('storage_path', models.CharField(max_length=500)),
                ('triggered_by', models.CharField(default='super_admin', max_length=150)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 Checksum', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for global system backups', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('paused', 'Paused / Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_subscriptions', to='core.saaspackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaaSPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bKash', 'bKash Merchant'), ('Nagad', 'Nagad Pay'), ('Bank Transfer', 'Direct Bank Wire'), ('Manual Cash', 'Cash Collection / Cheque'), ('Stripe', 'Stripe Card')], default='bKash', max_length=50)),
                ('trx_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending Verification'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_payments', to='core.tenant')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.tenantsubscription')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
