# Generated by Django 6.1 on 2026-09-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_token_hashes(apps, schema_editor):
    import hashlib
    import secrets
    TenantApiToken = apps.get_model('core', 'TenantApiToken')
    for token_obj in TenantApiToken.objects.all():
        if token_obj.token and not token_obj.token_hash:
            token_obj.token_hash = hashlib.sha256(token_obj.token.encode('utf-8')).hexdigest()
            token_obj.key_prefix = 'shb_' + token_obj.token[:6]
            token_obj.token = None
            token_obj.save(update_fields=['token_hash', 'key_prefix', 'token'])
        elif not token_obj.token_hash:
            raw = secrets.token_urlsafe(32)
            token_obj.token_hash = hashlib.sha256(raw.encode('utf-8')).hexdigest()
            token_obj.key_prefix = 'shb_' + raw[:6]
            token_obj.token = None
            token_obj.save(update_fields=['token_hash', 'key_prefix', 'token'])
        else:
            if token_obj.token:
                token_obj.token = None
                token_obj.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantapitoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='key_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(backfill_token_hashes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenantapitoken',
            name='token_hash',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='dns_challenge_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='verification_method',
            field=models.CharField(choices=[('dns_txt', 'DNS TXT Record'), ('platform_subdomain', 'Platform Subdomain (Auto-Verified)'), ('manual', 'Manual Admin Override')], default='dns_txt', max_length=30),
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantapitoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
