# Generated by Django 6.1 on 2026-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_milestone_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapitoken',
            name='rate_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Permitted requests per minute per credential'),
        ),
        migrations.AddField(
            model_name='tenantapitoken',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
