# Generated by Django 6.1 on 2026-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tenantapitoken_rate_limit_tenantapitoken_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='funbox_links',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of entertainment links [{name, url, category, icon}]'),
        ),
    ]
