# Generated by Django 6.1 on 2026-09-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companysetting_funbox_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApplication',
            fields=[
            ],
            options={
                'verbose_name': 'API Application',
                'verbose_name_plural': 'API Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tenantapitoken',),
        ),
    ]
