# Generated by Django 6.1 on 2026-09-26 09:49

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apiapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='funbox_live_tv_api_key',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='funbox_live_tv_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='funbox_live_tv_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='funbox_movie_server_api_key',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='funbox_movie_server_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='funbox_movie_server_url',
            field=models.URLField(blank=True),
        ),
    ]
