# Generated by Django 6.1 on 2026-09-27 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(db_index=True, max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_tenant_features', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'feature_key'],
                'indexes': [models.Index(fields=['tenant', 'feature_key', 'enabled'], name='tff_tenant_key_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'feature_key'), name='unique_tenant_feature_flag')],
            },
        ),
    ]
