# Generated by Django 6.1 on 2026-09-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenantfeatureflag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantfeatureflag',
            name='unique_tenant_feature_flag',
        ),
        migrations.RemoveIndex(
            model_name='tenantfeatureflag',
            name='tff_tenant_key_enabled_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tenantfeatureflag',
            unique_together={('tenant', 'feature_key')},
        ),
    ]
