# Generated by Django 6.1 on 2026-10-07 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='parent_tenant',
            field=models.ForeignKey(blank=True, help_text='Parent SaaS subscriber tenant. Null for top-level ISP/tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tenants', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['parent_tenant', 'is_active'], name='tenant_parent_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('parent_tenant', models.F('id')), _negated=True), name='tenant_not_self_parent'),
        ),
    ]
