# Generated by Django 6.1 on 2026-09-18 11:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0006_milestone_hardening'),
        ('core', '0010_tenantapitoken_rate_limit_tenantapitoken_status'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('network', '0011_popbranch_upstream_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('trade_license_no', models.CharField(blank=True, max_length=100)),
                ('bin_tin', models.CharField(blank=True, help_text='Business Identification Number / Tax ID', max_length=50)),
                ('contact_person', models.CharField(max_length=150)),
                ('billing_contact_email', models.EmailField(max_length=254)),
                ('billing_contact_phone', models.CharField(max_length=50)),
                ('committed_bandwidth_mbps', models.PositiveIntegerField(default=100, help_text='Committed Information Rate (CIR) in Mbps included in base fee.')),
                ('burst_rate_per_mbps', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Price per Mbps for burst overage above CIR (p95).', max_digits=10)),
                ('base_monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='Contracted flat base fee per billing cycle.', max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('CALENDAR_MONTH', 'Calendar Month'), ('ANNIVERSARY', 'Anniversary Date')], default='CALENDAR_MONTH', max_length=30)),
                ('credit_terms_days', models.PositiveIntegerField(default=30, help_text='Net payment terms in days from invoice generation.')),
                ('aggregation_policy', models.CharField(choices=[('AGGREGATE_SUM', 'Aggregate Circuit Sum'), ('PER_CIRCUIT', 'Per-Circuit Individual')], default='AGGREGATE_SUM', help_text='Whether multiple circuits are summed per 5-min bucket or calculated individually.', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Underlying customer anchoring BillingAccount and LedgerEntry.', on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_customers', to='core.tenant')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CorporateConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('circuit_id', models.CharField(db_index=True, help_text='Unique circuit identifier (e.g. CIR-DHK-001)', max_length=100)),
                ('name', models.CharField(help_text='e.g. Head Office Primary Leased Line', max_length=150)),
                ('service_location', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[('LEASED_LINE', 'Dedicated Leased Line'), ('METRO_ETHERNET', 'Metro Ethernet Circuit'), ('VLAN_TRUNK', '802.1Q VLAN Trunk'), ('PPPOE_ENTERPRISE', 'PPPoE Enterprise Tunnel'), ('STATIC_ROUTED', 'Static Routed IP Circuit')], default='LEASED_LINE', max_length=50)),
                ('interface_name', models.CharField(blank=True, default='', help_text='RouterOS interface name for telemetry (e.g. sfp-sfpplus1, ether2, vlan100)', max_length=100)),
                ('committed_bandwidth_mbps', models.PositiveIntegerField(default=50, help_text='Target bandwidth allocated to this specific link.')),
                ('burst_bandwidth_cap_mbps', models.PositiveIntegerField(default=100, help_text='Physical or queue burst ceiling for this link.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Provisioning'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISCONNECTED', 'Disconnected / Decommissioned')], db_index=True, default='ACTIVE', max_length=30)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_connections', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_connections', to='core.tenant')),
                ('corporate_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='corporate.corporatecustomer')),
            ],
            options={
                'ordering': ['corporate_customer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CorporateBillingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open for Collection'), ('CALCULATING', 'Calculation in Progress'), ('CALCULATED', 'Calculation Completed'), ('INVOICED', 'Invoiced'), ('FINALIZED', 'Finalized & Locked'), ('INSUFFICIENT_DATA', 'Insufficient Sample Coverage (<80%)')], db_index=True, default='OPEN', max_length=30)),
                ('total_samples', models.PositiveIntegerField(default=0)),
                ('coverage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('p95_inbound_mbps', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('p95_outbound_mbps', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('p95_billable_mbps', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('committed_mbps', models.PositiveIntegerField(default=0)),
                ('burst_mbps', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('burst_rate_per_mbps', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('burst_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculation_metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_period', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_billing_periods', to='core.tenant')),
                ('corporate_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='corporate.corporatecustomer')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CorporateIPPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Enterprise Static Block A', max_length=150)),
                ('network_cidr', models.CharField(help_text='e.g. 103.145.10.0/24', max_length=50)),
                ('gateway', models.GenericIPAddressField(help_text='Default gateway IP for the subnet')),
                ('dns_primary', models.GenericIPAddressField(default='8.8.8.8')),
                ('dns_secondary', models.GenericIPAddressField(default='1.1.1.1')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_ip_pools', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorporateIPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated to Circuit'), ('RESERVED', 'Reserved')], db_index=True, default='AVAILABLE', max_length=30)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedicated_ips', to='corporate.corporateconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_ip_addresses', to='core.tenant')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='corporate.corporateippool')),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='CorporateTrafficSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('inbound_bps', models.BigIntegerField(default=0, help_text='Average inbound bits per second')),
                ('outbound_bps', models.BigIntegerField(default=0, help_text='Average outbound bits per second')),
                ('inbound_bytes', models.BigIntegerField(default=0, help_text='Total inbound bytes in bucket')),
                ('outbound_bytes', models.BigIntegerField(default=0, help_text='Total outbound bytes in bucket')),
                ('collection_status', models.CharField(choices=[('SUCCESS', 'Success'), ('ESTIMATED', 'Estimated / Interpolated'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_samples', to='corporate.corporateconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_traffic_samples', to='core.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CorporateVLAN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vlan_id', models.PositiveIntegerField(help_text='802.1Q VLAN Tag (1–4094)')),
                ('name', models.CharField(help_text='e.g. VLAN-Corp-Grameenphone', max_length=100)),
                ('interface_name', models.CharField(default='ether1', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_assignment', to='corporate.corporateconnection')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_vlans', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_vlans', to='core.tenant')),
            ],
            options={
                'ordering': ['vlan_id'],
            },
        ),
        migrations.AddIndex(
            model_name='corporatecustomer',
            index=models.Index(fields=['tenant', 'status'], name='corp_cust_t_status_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatecustomer',
            index=models.Index(fields=['tenant', 'created_at'], name='corp_cust_t_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporatecustomer',
            constraint=models.UniqueConstraint(fields=('tenant', 'company_name'), name='unique_tenant_corporate_company'),
        ),
        migrations.AddIndex(
            model_name='corporateconnection',
            index=models.Index(fields=['tenant', 'status'], name='corp_conn_t_status_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateconnection',
            index=models.Index(fields=['tenant', 'corporate_customer'], name='corp_conn_t_cust_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporateconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'circuit_id'), name='unique_tenant_corp_circuit_id'),
        ),
        migrations.AddIndex(
            model_name='corporatebillingperiod',
            index=models.Index(fields=['tenant', 'status'], name='corp_period_t_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporatebillingperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'corporate_customer', 'period_start', 'period_end'), name='unique_tenant_corporate_period'),
        ),
        migrations.AddConstraint(
            model_name='corporateippool',
            constraint=models.UniqueConstraint(fields=('tenant', 'network_cidr'), name='unique_tenant_ip_pool_cidr'),
        ),
        migrations.AddIndex(
            model_name='corporateipaddress',
            index=models.Index(fields=['tenant', 'status'], name='corp_ip_t_status_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateipaddress',
            index=models.Index(fields=['tenant', 'connection'], name='corp_ip_t_conn_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporateipaddress',
            constraint=models.UniqueConstraint(fields=('tenant', 'ip_address'), name='unique_tenant_corporate_ip'),
        ),
        migrations.AddIndex(
            model_name='corporatetrafficsample',
            index=models.Index(fields=['tenant', 'connection', 'timestamp'], name='corp_sample_t_c_time_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatetrafficsample',
            index=models.Index(fields=['tenant', 'timestamp'], name='corp_sample_t_time_idx'),
        ),
        migrations.AddIndex(
            model_name='corporatevlan',
            index=models.Index(fields=['tenant', 'vlan_id'], name='corp_vlan_t_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='corporatevlan',
            constraint=models.UniqueConstraint(fields=('tenant', 'router', 'vlan_id'), name='unique_tenant_router_vlan'),
        ),
    ]
