# Generated by Django 6.1 on 2026-09-01 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('billing_month', models.CharField(help_text='e.g. September 2026', max_length=20)),
                ('package_name', models.CharField(max_length=150)),
                ('package_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid / Due'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mikrotik_profile', models.CharField(help_text='Corresponding MikroTik PPP Profile name', max_length=150)),
                ('speed_mbps', models.PositiveIntegerField(default=10, help_text='Download speed in Mbps')),
                ('upload_speed_mbps', models.PositiveIntegerField(default=10, help_text='Upload speed in Mbps')),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('regular_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('min_reseller_price', models.DecimalField(decimal_places=2, default=350.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('old_expiry', models.DateField(blank=True, null=True)),
                ('new_expiry', models.DateField()),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('trx_id', models.CharField(blank=True, max_length=100)),
                ('is_reversed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
