# Generated by Django 6.1 on 2026-09-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='package',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_records', to='billing.package'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.staffprofile'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='resellerpricing',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_rates', to='billing.package'),
        ),
        migrations.AddField(
            model_name='resellerpricing',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='authentication.staffprofile'),
        ),
        migrations.AddField(
            model_name='resellerpricing',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_pricings', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='resellerpricing',
            unique_together={('reseller', 'package')},
        ),
    ]
