# Generated by Django 6.1 on 2026-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('billing', '0003_offer'),
        ('core', '0004_companysetting_advance_loan_sms_template_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='inv_tenant_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'created_at'], name='inv_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='inv_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['tenant', 'created_at'], name='rech_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recharge',
            index=models.Index(fields=['customer', 'created_at'], name='rech_customer_created_idx'),
        ),
    ]
