# Generated by Django 6.1 on 2026-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_options_and_more'),
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_package_name'),
        ),
    ]
