# Generated by Django 6.1 on 2026-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_package_unique_tenant_package_name'),
        ('core', '0009_milestone_hardening'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'billing_month'), name='unique_invoice_per_customer_per_month'),
        ),
    ]
