# Generated by Django 6.1 on 2026-09-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_milestone_hardening'),
        ('core', '0011_companysetting_funbox_links'),
        ('customers', '0005_customer_portal_password'),
        ('network', '0016_onu_mactable_onu_temperature_onu_uptime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthDailyUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_date', models.DateField(help_text='Local date the bytes were consumed on')),
                ('rx_bytes', models.BigIntegerField(default=0, help_text='Client upload (router RX) in bytes')),
                ('tx_bytes', models.BigIntegerField(default=0, help_text='Client download (router TX) in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_daily_usage', to='customers.customer')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandwidth_daily_usage', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_daily_usage', to='core.tenant')),
            ],
            options={
                'ordering': ['-usage_date'],
                'indexes': [models.Index(fields=['tenant', 'usage_date'], name='bdu_tenant_date_idx'), models.Index(fields=['customer', 'usage_date'], name='bdu_customer_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'usage_date'), name='unique_customer_daily_bandwidth')],
            },
        ),
    ]
