# Generated by Django 6.1 on 2026-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bandwidthdailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthdailyusage',
            name='last_rx_snapshot',
            field=models.BigIntegerField(default=0, help_text='Router cumulative RX counter observed at the previous aggregation tick.'),
        ),
        migrations.AddField(
            model_name='bandwidthdailyusage',
            name='last_tx_snapshot',
            field=models.BigIntegerField(default=0, help_text='Router cumulative TX counter observed at the previous aggregation tick.'),
        ),
    ]
