# Generated by Django 6.1 on 2026-09-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_bandwidthdailyusage_last_rx_snapshot_and_more'),
        ('core', '0012_apiapplication'),
        ('customers', '0005_customer_portal_password'),
        ('network', '0017_networksyncjob_correlation_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bandwidthdailyusage',
            constraint=models.CheckConstraint(condition=models.Q(('rx_bytes__gte', 0), ('tx_bytes__gte', 0)), name='bdu_bytes_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bandwidthdailyusage',
            constraint=models.CheckConstraint(condition=models.Q(('last_rx_snapshot__gte', 0), ('last_tx_snapshot__gte', 0)), name='bdu_snapshots_non_negative'),
        ),
    ]
