# Generated by Django 6.1 on 2026-10-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_coupon_code_invoice_coupon_discount_and_more'),
        ('customers', '0008_alter_customer_status_customerservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customerservice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customersubscription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('UNPAID', 'Unpaid / Due'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], default='UNPAID', max_length=20),
        ),
    ]
