# Generated by Django 6.1 on 2026-09-07 02:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_alter_invoice_options_and_more'),
        ('core', '0006_tenantdomain_auditlog_after_auditlog_before_and_more'),
        ('customers', '0003_alter_customer_bill_date'),
        ('payments', '0005_inboundpaymentevent_paymentattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('INVOICE', 'Invoice raised'), ('PAYMENT', 'Payment received'), ('RECHARGE', 'Service recharge'), ('ADVANCE', 'Advance/prepayment'), ('REFUND', 'Refund issued'), ('REVERSAL', 'Transaction reversal'), ('ADJUSTMENT', 'Manual adjustment'), ('COMMISSION', 'Reseller commission'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_NOTE', 'Debit note')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_id', models.CharField(blank=True, help_text='UUID of related Invoice, Payment, Recharge, etc.', max_length=100)),
                ('reference_type', models.CharField(blank=True, help_text="Model name: 'Invoice', 'PaymentTransaction', 'Recharge'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('CREDIT', 'Credit (add to balance)'), ('DEBIT', 'Debit (deduct from balance)'), ('WAIVER', 'Fee waiver'), ('PENALTY', 'Late payment penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('approved_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment', to='finance.ledgerentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.paymenttransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current account balance (positive = advance, negative = due)', max_digits=14)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_accounts', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'customer'], name='billing_acct_tenant_cust_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('operation', models.CharField(help_text="e.g. 'recharge', 'payment', 'webhook'", max_length=100)),
                ('request_hash', models.CharField(blank=True, help_text='SHA256 of request body for exact-match deduplication', max_length=64)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField(default=200)),
                ('status', models.CharField(choices=[('PROCESSING', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Idempotency records expire and can be GC'd after this time", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'key'], name='idem_tenant_key_idx'), models.Index(fields=['expires_at'], name='idem_expires_idx')],
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='ledger_tenant_cust_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'entry_type', 'created_at'], name='ledger_tenant_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['tenant', 'customer'], name='adj_tenant_cust_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['tenant', 'invoice'], name='allocation_tenant_inv_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['tenant', 'payment'], name='allocation_tenant_pay_idx'),
        ),
    ]
