# Generated by Django 6.1 on 2026-09-26 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_bandwidthdailyusage_bdu_bytes_non_negative_and_more'),
        ('customers', '0005_customer_portal_password'),
        ('finance', '0001_initial'),
        ('payments', '0007_encrypt_payment_gateway_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.paymenttransaction'),
        ),
    ]
