# Generated by Django 6.1 on 2026-09-26 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_bandwidthdailyusage_bdu_bytes_non_negative_and_more'),
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        ('customers', '0006_customer_cpe_admin_password_and_more'),
        ('finance', '0002_alter_adjustment_customer_alter_ledgerentry_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed amount')], max_length=15)),
                ('value', models.DecimalField(decimal_places=2, help_text='% (0-100) if PERCENTAGE, else ৳ value', max_digits=12)),
                ('min_invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('redemptions', models.PositiveIntegerField(default=0)),
                ('per_customer_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_coupons', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='core.tenant')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_records', to='finance.discountcoupon')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('days_overdue', models.PositiveIntegerField(help_text='Trigger when invoice is at least N days past due_date.')),
                ('action', models.CharField(choices=[('SMS', 'SMS reminder'), ('IVR', 'IVR voice call'), ('EMAIL', 'Email'), ('DISCONNECT', 'Network disconnection'), ('TICKET', 'Create support ticket'), ('NOTE', 'Collection note only')], default='SMS', max_length=20)),
                ('template_text', models.TextField(blank=True, help_text='Optional SMS/IVR template. Supports [NAME] [AMOUNT] [DAYS] [DATE] placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_stages', to='core.tenant')),
            ],
            options={
                'ordering': ['days_overdue'],
            },
        ),
        migrations.CreateModel(
            name='DunningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='queued', help_text='queued | sent | failed | pending', max_length=30)),
                ('provider_response', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dunning_events', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dunning_events', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_events', to='core.tenant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.dunningstage')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='VAT', max_length=80)),
                ('percentage', models.DecimalField(decimal_places=3, default=0.0, help_text='Tax percentage (e.g. 5.000 = 5%)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rule', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BillDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20)),
                ('support_ticket_id', models.CharField(blank=True, default='', max_length=64)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_disputes', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='billing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_disputes', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='bill_dispute_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('REVERSAL', 'Recharge reversal'), ('OVERPAYMENT', 'Overpayment'), ('GOODWILL', 'Goodwill'), ('CORRECTION', 'Error correction'), ('WAIVER', 'Billing waiver')], default='REVERSAL', max_length=20)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued (unused)'), ('APPLIED', 'Applied to invoice'), ('REFUNDED', 'Refunded out')], default='ISSUED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, default='system', max_length=150)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='customers.customer')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.invoice')),
                ('related_recharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.recharge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='core.tenant')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', 'status'], name='cn_tenant_cust_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='discountcoupon',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='coupon_tenant_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['tenant', 'coupon'], name='redemption_tenant_coupon_idx'),
        ),
        migrations.AddConstraint(
            model_name='dunningstage',
            constraint=models.UniqueConstraint(fields=('tenant', 'days_overdue'), name='dunning_stage_tenant_days_uniq'),
        ),
        migrations.AddIndex(
            model_name='dunningevent',
            index=models.Index(fields=['tenant', 'triggered_at'], name='dunning_event_tenant_idx'),
        ),
    ]
