# Generated by Django 6.1 on 2026-09-07 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0006_tenantdomain_auditlog_after_auditlog_before_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="Dot-notation capability, e.g. 'customer.recharge'", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('module', models.CharField(help_text="Domain module, e.g. 'customers', 'network'", max_length=50)),
            ],
            options={
                'ordering': ['module', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission % on each customer recharge', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resellers', to='core.tenant')),
                ('user', models.OneToOneField(help_text='Primary login user for this reseller account', on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit (Top-up)'), ('DEBIT', 'Debit (Recharge cost)'), ('COMMISSION', 'Commission earned'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Manual adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Invoice/Recharge/TrxID', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='authentication.reseller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='authentication.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global (all data)'), ('TENANT', 'Tenant-wide'), ('POP', 'POP / Branch'), ('AREA', 'Geographic Area'), ('SELF', 'Own records only'), ('ASSIGNED', 'Assigned records only')], default='TENANT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='authentication.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant', 'user'],
            },
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['tenant', 'is_active'], name='reseller_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerledgerentry',
            index=models.Index(fields=['reseller', 'created_at'], name='reseller_ledger_ts_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='staffmembership',
            index=models.Index(fields=['user', 'tenant', 'is_active'], name='membership_user_tenant_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffmembership',
            unique_together={('user', 'tenant')},
        ),
    ]
