# Generated by Django 6.1 on 2026-09-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_permission_reseller_resellerledgerentry_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin / Managing Director'), ('BILLING', 'Billing Operator'), ('SALES', 'Sales Executive'), ('DEMO', 'Demo Accounts Manager'), ('TECHNICIAN', 'NOC / Field Technician'), ('STAFF', 'General Staff'), ('RESELLER_L1', 'Reseller (Level 1 POP)'), ('RESELLER_L2', 'Sub Reseller (Level 2 POP)'), ('DISTRIBUTOR', 'Hardware / Card Distributor'), ('BANDWIDTH_RESELLER', 'Bandwidth Carrier Reseller'), ('BILLING_OPERATOR', 'Billing Operator'), ('SUPPORT_STAFF', 'Support Staff'), ('LINE_MAN', 'Line Man / Field Tech'), ('RESELLER', 'Reseller / Master Sub-ISP'), ('AGENT', 'Local Agent'), ('CUSTOMER', 'Customer / Subscriber')], default='ADMIN', max_length=30),
        ),
    ]
