# Generated by Django 6.1 on 2026-09-27 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_seed_rbac_catalog'),
        ('core', '0014_tenantfeatureflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('context_type', models.CharField(choices=[('tenant', 'ISP Tenant Staff'), ('central_admin', 'SaaS Control Plane Admin'), ('reseller', 'ISP Reseller')], default='tenant', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('tenant', models.ForeignKey(blank=True, help_text='Resolved ISP tenant. Null for central_admin sessions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='authenticat_user_id_896eb4_idx'), models.Index(fields=['tenant', '-created_at'], name='authenticat_tenant__53231a_idx'), models.Index(fields=['context_type', '-created_at'], name='authenticat_context_57277b_idx')],
            },
        ),
    ]
