# Generated by Django 6.1 on 2026-10-09 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_authsession'),
        ('core', '0019_backfill_legacy_organization'),
        ('customers', '0009_customerservice_provisioning_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_assignments', to='customers.customer')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='authentication.reseller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_assignments', to='core.tenant')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['tenant', 'reseller', 'is_active'], name='reseller_cust_active_idx'), models.Index(fields=['tenant', 'customer', 'is_active'], name='customer_reseller_active_idx')],
                'unique_together': {('reseller', 'customer')},
            },
        ),
    ]
