# Generated by Django 6.1 on 2026-10-09 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_resellercustomer'),
        ('core', '0019_backfill_legacy_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerCreditFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_exposure', models.DecimalField(decimal_places=2, default=0, help_text='Cached: sum of pending+finalized credit holds and draws.', max_digits=14)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_facility', to='authentication.reseller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_credit_facilities', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerCreditApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Facility created'), ('LIMIT_CHANGE', 'Limit change'), ('SUSPEND', 'Suspended'), ('REACTIVATE', 'Reactivated'), ('REPAY', 'Repayment applied')], max_length=20)),
                ('previous_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('actor_username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='authentication.resellercreditfacility')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', '-created_at'], name='credit_approval_history_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('gross_collections', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('isp_share', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wallet_credit_applied', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('CLOSED', 'Closed'), ('DISPUTED', 'Disputed')], default='OPEN', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='authentication.reseller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_settlements', to='core.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['reseller', 'status'], name='settlement_reseller_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerWalletHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('WALLET', 'Wallet cash'), ('CREDIT', 'Credit facility')], default='WALLET', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RELEASED', 'Released'), ('FINALIZED', 'Finalized'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('purpose', models.CharField(help_text="What this hold is for, e.g. 'package_purchase' or 'renewal'", max_length=100)),
                ('reference_id', models.CharField(blank=True, help_text='UUID of the related network job, recharge, etc.', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_holds', to='authentication.reseller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_holds', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reseller', 'status', '-created_at'], name='reseller_hold_active_idx'), models.Index(fields=['tenant', 'status'], name='reseller_hold_tenant_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('reseller', 'idempotency_key'), name='reseller_hold_idem_unique')],
            },
        ),
    ]
