# Generated by Django 6.1 on 2026-10-09 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_resellercreditfacility_resellercreditapproval_and_more'),
        ('billing', '0011_invoice_service_invoice_subscription_and_more'),
        ('core', '0019_backfill_legacy_organization'),
        ('customers', '0009_customerservice_provisioning_status'),
        ('payments', '0009_paymenttransaction_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerCollectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash to ISP account'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('BANK', 'Bank transfer'), ('OTHER', 'Other')], default='CASH', max_length=12)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received from customer'), ('ALLOCATED', 'Allocated to customer invoice/recharge'), ('PENDING_REVIEW', 'Awaiting manual review'), ('REVERSED', 'Reversed by an administrator')], default='RECEIVED', max_length=20)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reseller_collections', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_collections', to='billing.invoice')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_collections', to='payments.paymenttransaction')),
                ('recharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_collections', to='billing.recharge')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='authentication.reseller')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='authentication.resellersettlement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_collections', to='core.tenant')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['tenant', 'reseller', 'status'], name='coll_tr_stat_idx'), models.Index(fields=['tenant', 'status', 'collected_at'], name='coll_t_stat_ts_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('tenant', 'reseller', 'reference'), name='reseller_collection_ref_unique')],
            },
        ),
    ]
