# Generated by Django 6.1 on 2026-09-01 13:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(choices=[('HUAWEI', 'Huawei'), ('ZTE', 'ZTE'), ('VSOL', 'V-SOL'), ('BDCOM', 'BDCOM'), ('CDATA', 'C-Data'), ('OTHER', 'Generic/Other')], default='VSOL', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('snmp_community', models.CharField(default='public', max_length=100)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('telnet_port', models.PositiveIntegerField(default=23)),
                ('telnet_user', models.CharField(blank=True, max_length=100)),
                ('telnet_password', models.CharField(blank=True, max_length=255)),
                ('pon_ports_count', models.PositiveIntegerField(default=8)),
                ('total_onus', models.PositiveIntegerField(default=0)),
                ('online_onus', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olts', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pon_port', models.CharField(help_text='e.g. EPON0/1 or 1/1/1', max_length=50)),
                ('onu_index', models.PositiveIntegerField(default=1)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('rx_power', models.DecimalField(decimal_places=2, default=-19.5, help_text='Optical RX Power in dBm', max_digits=5)),
                ('tx_power', models.DecimalField(decimal_places=2, default=2.1, help_text='Optical TX Power in dBm', max_digits=5)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('DyingGasp', 'Power Loss (Dying Gasp)'), ('Los', 'Loss of Signal (LOS)')], default='Online', max_length=30)),
                ('distance_meters', models.PositiveIntegerField(default=0)),
                ('last_offline_reason', models.CharField(blank=True, max_length=255)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='network.olt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('api_port', models.PositiveIntegerField(default=8728)),
                ('api_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('winbox_port', models.PositiveIntegerField(default=8291)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Error', 'Error')], default='Online', max_length=20)),
                ('cpu_usage', models.PositiveIntegerField(default=0, help_text='CPU load %')),
                ('memory_usage', models.PositiveIntegerField(default=0, help_text='Memory load %')),
                ('active_pppoe_count', models.PositiveIntegerField(default=0)),
                ('total_customers_count', models.PositiveIntegerField(default=0)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('caller_id', models.CharField(blank=True, max_length=100)),
                ('uptime', models.CharField(default='0s', max_length=50)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='core.tenant')),
            ],
        ),
    ]
