# Generated by Django 6.1 on 2026-09-01 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POPBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('in_charge', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('total_capacity', models.PositiveIntegerField(default=1000)),
                ('power_backup', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Decommissioned', 'Decommissioned / Left')], default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.tenant')),
            ],
        ),
    ]
