# Generated by Django 6.1 on 2026-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_popbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
