# Generated by Django 6.1 on 2026-09-07 02:36

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_router_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='api_protocol',
            field=models.CharField(choices=[('REST', 'RouterOS REST API (HTTPS)'), ('API', 'RouterOS Binary API (Port 8728)')], default='REST', help_text='Protocol used for automated device management', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='connection_timeout',
            field=models.PositiveIntegerField(default=10, help_text='Connection timeout in seconds'),
        ),
        migrations.AddField(
            model_name='router',
            name='disk_usage',
            field=models.PositiveIntegerField(default=0, help_text='Disk usage %'),
        ),
        migrations.AddField(
            model_name='router',
            name='hostname',
            field=models.CharField(blank=True, default='', help_text='Router hostname / FQDN', max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='https_port',
            field=models.PositiveIntegerField(default=443, help_text='RouterOS HTTPS REST API port'),
        ),
        migrations.AddField(
            model_name='router',
            name='retry_count',
            field=models.PositiveIntegerField(default=2, help_text='Number of retry attempts on network error'),
        ),
        migrations.AddField(
            model_name='router',
            name='routeros_version',
            field=models.CharField(blank=True, default='', help_text='RouterOS Version (e.g. 7.14.3)', max_length=50),
        ),
        migrations.AddField(
            model_name='router',
            name='ssl_verify',
            field=models.BooleanField(default=False, help_text='Verify SSL certificate on HTTPS connection'),
        ),
        migrations.AddField(
            model_name='router',
            name='uptime',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='olt',
            name='snmp_community',
            field=apps.core.fields.EncryptedCharField(default='public', max_length=500),
        ),
        migrations.AlterField(
            model_name='olt',
            name='telnet_password',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_port',
            field=models.PositiveIntegerField(default=8728, help_text='Legacy RouterOS binary API port'),
        ),
        migrations.AlterField(
            model_name='router',
            name='password',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
    ]
