# Generated by Django 6.1 on 2026-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('network', '0004_router_api_protocol_router_connection_timeout_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='olt',
            constraint=models.UniqueConstraint(fields=('tenant', 'ip_address'), name='unique_tenant_olt_ip'),
        ),
        migrations.AddConstraint(
            model_name='olt',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_olt_name'),
        ),
        migrations.AddConstraint(
            model_name='popbranch',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_pop_name'),
        ),
        migrations.AddConstraint(
            model_name='router',
            constraint=models.UniqueConstraint(fields=('tenant', 'ip_address'), name='unique_tenant_router_ip'),
        ),
        migrations.AddConstraint(
            model_name='router',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_router_name'),
        ),
        migrations.AddConstraint(
            model_name='router',
            constraint=models.UniqueConstraint(condition=models.Q(('hostname', ''), _negated=True), fields=('tenant', 'hostname'), name='unique_tenant_router_hostname'),
        ),
    ]
