# Generated by Django 6.1 on 2026-09-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('network', '0005_olt_unique_tenant_olt_ip_olt_unique_tenant_olt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='customers.customer'),
        ),
    ]
