# Generated by Django 6.1 on 2026-09-09 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('network', '0006_onu_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ENABLE_USER', 'Enable PPPoE / Hotspot User'), ('DISABLE_USER', 'Disable User / Cut Internet'), ('UPDATE_PACKAGE', 'Update Speed Profile / Package'), ('DISCONNECT_SESSION', 'Disconnect Active Session'), ('SYNC_ROUTER', 'Sync Router Configuration'), ('REBOOT_ONU', 'Reboot ONU')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Completed Successfully'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_sync_jobs', to='customers.customer')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='network.olt')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_sync_jobs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='netsync_tenant_status_idx'), models.Index(fields=['tenant', 'created_at'], name='netsync_tenant_created_idx')],
            },
        ),
    ]
