# Generated by Django 6.1 on 2026-09-09 13:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_package_unique_tenant_package_name'),
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('network', '0007_networksyncjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_by', models.CharField(default='system', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_evaluated', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('missing_in_router_count', models.PositiveIntegerField(default=0)),
                ('unknown_in_erp_count', models.PositiveIntegerField(default=0)),
                ('profile_mismatch_count', models.PositiveIntegerField(default=0)),
                ('status_mismatch_count', models.PositiveIntegerField(default=0)),
                ('router_mismatch_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PPPoESecretItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('reconciliation_status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISSING_IN_ROUTER', 'Missing in Router'), ('UNKNOWN_IN_ERP', 'Unknown in ERP (Orphan)'), ('PROFILE_MISMATCH', 'Profile Mismatch'), ('STATUS_MISMATCH', 'Status Mismatch'), ('ROUTER_MISMATCH', 'Router Mismatch'), ('ERROR', 'Error')], db_index=True, default='MATCHED', max_length=30)),
                ('router_profile', models.CharField(blank=True, default='', max_length=150)),
                ('expected_profile', models.CharField(blank=True, default='', max_length=150)),
                ('router_disabled', models.BooleanField(blank=True, null=True)),
                ('expected_disabled', models.BooleanField(blank=True, null=True)),
                ('router_comment', models.CharField(blank=True, default='', max_length=255)),
                ('router_caller_id', models.CharField(blank=True, default='', max_length=100)),
                ('router_service', models.CharField(blank=True, default='pppoe', max_length=50)),
                ('discrepancy_details', models.JSONField(blank=True, default=dict)),
                ('last_reconciled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pppoe_secrets', to='customers.customer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pppoe_secrets', to='billing.package')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_secrets', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_secrets', to='core.tenant')),
            ],
            options={
                'ordering': ['username'],
                'indexes': [models.Index(fields=['tenant', 'reconciliation_status'], name='pppoe_tenant_status_idx'), models.Index(fields=['tenant', 'router', 'reconciliation_status'], name='pppoe_t_r_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'router', 'username'), name='unique_tenant_router_secret_username')],
            },
        ),
    ]
