# Generated by Django 6.1 on 2026-09-09 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('network', '0008_reconciliationrun_pppoesecretitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksyncjob',
            name='actor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='current_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='requested_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='target_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='target_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='target_type',
            field=models.CharField(default='customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='networksyncjob',
            name='action',
            field=models.CharField(choices=[('ENABLE_SERVICE', 'Enable Service'), ('DISABLE_SERVICE', 'Disable Service'), ('RECONNECT', 'Reconnect'), ('CHANGE_PACKAGE', 'Change Package / Profile'), ('SYNC_SECRET', 'Synchronize PPPoE Secret'), ('SYNC_PROFILE', 'Synchronize Profile'), ('SYNC_ROUTER', 'Router Synchronization'), ('RETRY_FAILED', 'Retry Failed Synchronization'), ('ENABLE_USER', 'Enable PPPoE / Hotspot User'), ('DISABLE_USER', 'Disable User / Cut Internet'), ('UPDATE_PACKAGE', 'Update Speed Profile / Package'), ('DISCONNECT_SESSION', 'Disconnect Active Session'), ('REBOOT_ONU', 'Reboot ONU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='networksyncjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Execution'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Completed Successfully'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkNetworkBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('PREVIEWED', 'Previewed'), ('QUEUED', 'Queued'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_batches', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_network_batches', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='network.bulknetworkbatch'),
        ),
        migrations.AddIndex(
            model_name='networksyncjob',
            index=models.Index(fields=['tenant', 'idempotency_key'], name='netsync_idempotency_idx'),
        ),
        migrations.AddIndex(
            model_name='bulknetworkbatch',
            index=models.Index(fields=['tenant', 'status'], name='bulk_batch_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bulknetworkbatch',
            index=models.Index(fields=['tenant', 'created_at'], name='bulk_batch_tenant_created_idx'),
        ),
    ]
