# Generated by Django 6.1 on 2026-09-09 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('network', '0009_networksyncjob_actor_networksyncjob_current_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='pop_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olts', to='network.popbranch'),
        ),
        migrations.AddField(
            model_name='olt',
            name='upstream_router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_olts', to='network.router'),
        ),
        migrations.AddField(
            model_name='onu',
            name='auto_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onu',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onu',
            name='optical_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('LOS', 'Loss of Signal (LOS)'), ('PowerLoss', 'Power Loss (Dying Gasp)')], default='Normal', max_length=30),
        ),
        migrations.AddField(
            model_name='onu',
            name='reconciliation_status',
            field=models.CharField(choices=[('MATCHED', 'Matched'), ('MISSING_IN_OLT', 'Missing in OLT'), ('UNKNOWN_IN_ERP', 'Unknown in ERP (Unbound)'), ('BINDING_MISMATCH', 'Binding Mismatch'), ('OPTICAL_ALARM', 'Optical Alarm')], default='MATCHED', max_length=30),
        ),
        migrations.AddField(
            model_name='popbranch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='popbranch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OLTReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_by', models.CharField(default='system', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_evaluated', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('missing_in_olt_count', models.PositiveIntegerField(default=0)),
                ('unknown_in_erp_count', models.PositiveIntegerField(default=0)),
                ('binding_mismatch_count', models.PositiveIntegerField(default=0)),
                ('optical_alarm_count', models.PositiveIntegerField(default=0)),
                ('discrepancy_details', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='network.olt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olt_reconciliation_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSessionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('caller_id', models.CharField(blank=True, max_length=100)),
                ('connected_at', models.DateTimeField()),
                ('disconnected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('terminate_cause', models.CharField(default='Admin-Reset', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_history', to='customers.customer')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_history', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_session_history', to='core.tenant')),
            ],
            options={
                'ordering': ['-disconnected_at'],
                'indexes': [models.Index(fields=['tenant', 'username'], name='hist_tenant_user_idx'), models.Index(fields=['tenant', 'disconnected_at'], name='hist_tenant_disc_idx')],
            },
        ),
    ]
