# Generated by Django 6.1 on 2026-09-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_olt_latitude_olt_longitude_olt_pop_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popbranch',
            name='upstream_router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_pops', to='network.router'),
        ),
    ]
