# Generated by Django 6.1 on 2026-09-19 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tenantapitoken_rate_limit_tenantapitoken_status'),
        ('network', '0011_popbranch_upstream_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='TJBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Box identifier or code, e.g. BOX-A1', max_length=150)),
                ('box_category', models.CharField(choices=[('Master Box', 'Master Box'), ('Splitter Box', 'Splitter Box'), ('Zone/point Box', 'Zone/point Box')], default='Master Box', max_length=50)),
                ('fiber_code', models.JSONField(blank=True, default=list, help_text='Structured fiber lines array: category, in_out, brand, code, cores')),
                ('lat_long', models.CharField(blank=True, default='', help_text='e.g. 23.8103, 90.4125', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes, sub-zone identifiers, or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tj_boxes', to='core.tenant')),
                ('zone', models.ForeignKey(blank=True, help_text='Associated POP distribution zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tj_boxes', to='network.popbranch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'name'], name='tjbox_tenant_name_idx'), models.Index(fields=['tenant', 'zone'], name='tjbox_tenant_zone_idx')],
            },
        ),
    ]
