# Generated by Django 6.1 on 2026-09-19 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companysetting_funbox_links'),
        ('network', '0012_tjbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireGuardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wg_ip', models.CharField(help_text='WireGuard client tunnel IP CIDR, e.g. 10.255.0.2/30', max_length=64)),
                ('mik_public_key', models.CharField(help_text='MikroTik WireGuard public key', max_length=128)),
                ('mik_private_key_enc', models.TextField(blank=True, default='', help_text='AES-256 encrypted private key')),
                ('mik_private_key_set', models.BooleanField(default=False)),
                ('vps_public_key', models.CharField(help_text='Server WireGuard public key', max_length=128)),
                ('endpoint_ip', models.CharField(help_text='Server VPS host or IP', max_length=128)),
                ('endpoint_port', models.PositiveIntegerField(default=51820)),
                ('allowed_ips', models.CharField(default='0.0.0.0/0', max_length=255)),
                ('snmp_community', models.CharField(default='public', max_length=64)),
                ('router_name', models.CharField(default='MikroTik', max_length=128)),
                ('router_location', models.CharField(blank=True, default='', max_length=255)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('is_reachable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(blank=True, help_text='Optional link to a specific router. If null, acts as the tenant default hub.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireguard_configs', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireguard_configs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WireGuardSubnet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subnet', models.CharField(help_text='Subnet CIDR, e.g. 172.25.28.0/24', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_subnets', to='network.olt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireguard_subnets', to='core.tenant')),
                ('vpn_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='network.wireguardconfig')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wireguardconfig',
            index=models.Index(fields=['tenant', 'router'], name='wg_tenant_router_idx'),
        ),
    ]
