# Generated by Django 6.1 on 2026-09-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_wireguard_integrity_and_encrypted_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='mactable',
            field=models.JSONField(blank=True, default=list, help_text='Learned customer CPE MAC addresses and VLANs from OLT'),
        ),
        migrations.AddField(
            model_name='onu',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optical module temperature in °C', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='onu',
            name='uptime',
            field=models.CharField(blank=True, default='', help_text='ONU alive time / uptime from OLT', max_length=50),
        ),
        migrations.AlterField(
            model_name='olt',
            name='brand',
            field=models.CharField(choices=[('HUAWEI', 'Huawei'), ('ZTE', 'ZTE'), ('VSOL', 'V-SOL'), ('BDCOM', 'BDCOM'), ('CDATA', 'C-Data'), ('HSGQ', 'HSGQ'), ('OTHER', 'Generic/Other')], default='VSOL', max_length=50),
        ),
    ]
