# Generated by Django 6.1 on 2026-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apiapplication'),
        ('customers', '0005_customer_portal_password'),
        ('network', '0016_onu_mactable_onu_temperature_onu_uptime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksyncjob',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='device_identity',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksyncjob',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='networksyncjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('SUCCESS', 'Completed Successfully'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled'), ('STALE', 'Stale / Timed Out')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='networksyncjob',
            index=models.Index(fields=['tenant', 'correlation_id'], name='netsync_tenant_corr_idx'),
        ),
        migrations.AddIndex(
            model_name='networksyncjob',
            index=models.Index(fields=['tenant', 'device_identity'], name='netsync_tenant_dev_idx'),
        ),
    ]
