# Generated by Django 6.1 on 2026-09-26 11:19

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_networksyncjob_correlation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='cli_enable_password',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='olt',
            name='cli_enabled',
            field=models.BooleanField(default=False, help_text='Enable CLI/Telnet fallback'),
        ),
        migrations.AddField(
            model_name='olt',
            name='cli_timeout',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='olt',
            name='poll_interval',
            field=models.PositiveIntegerField(default=600, help_text='Poll interval in seconds'),
        ),
        migrations.AddField(
            model_name='olt',
            name='snmp_retries',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='router',
            name='nas_identifier',
            field=models.CharField(blank=True, default='', help_text='NAS-Identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_acct_port',
            field=models.PositiveIntegerField(default=1813, help_text='RADIUS Accounting UDP Port'),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_auth_port',
            field=models.PositiveIntegerField(default=1812, help_text='RADIUS Authentication UDP Port'),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_coa_port',
            field=models.PositiveIntegerField(default=3799, help_text='RADIUS CoA / Disconnect-Request (PoD) UDP Port'),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', help_text='RADIUS Shared Secret', max_length=255),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_protocol',
            field=models.CharField(choices=[('REST', 'RouterOS REST API (HTTPS)'), ('API', 'RouterOS Binary API (Port 8728)'), ('RADIUS', 'RADIUS AAA (Authentication & Accounting)')], default='REST', help_text='Protocol used for automated device management', max_length=20),
        ),
    ]
