# Generated by Django 6.1 on 2026-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_olt_cli_enable_password_olt_cli_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='expire_local_address',
            field=models.GenericIPAddressField(default='172.31.250.1', help_text='Default gateway IP for expired pool'),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_pool_enabled',
            field=models.BooleanField(default=True, help_text='Route expired prepaid users to low-speed captive pool instead of hard disconnect'),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_pool_name',
            field=models.CharField(default='expired_pool', max_length=64),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_pool_network',
            field=models.CharField(default='172.31.250.10-172.31.250.250', help_text='IP range leased to expired subscribers', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_profile_name',
            field=models.CharField(default='sheba_expired_profile', max_length=64),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_rate_limit',
            field=models.CharField(default='32k/32k', help_text='Throttled bandwidth rate limit for expired users (10k-50k allowed, e.g. 10k/50k)', max_length=30),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_redirect_url',
            field=models.CharField(blank=True, default='', help_text='Payment portal URL for captive popup redirection', max_length=255),
        ),
        migrations.AddField(
            model_name='router',
            name='expire_walled_garden',
            field=models.TextField(blank=True, default='bkash.com,nagad.com.bd,sslcommerz.com,shurjopay.com.bd,rocket.dutchbanglabank.com', help_text='Comma-separated payment domains allowed in captive mode'),
        ),
    ]
