# Generated by Django 6.1 on 2026-09-26 14:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        ('network', '0019_router_expire_local_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('interfaces', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, default='')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_snapshots', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_snapshots', to='core.tenant')),
            ],
            options={
                'ordering': ['-snapshot_date', '-captured_at'],
                'indexes': [models.Index(fields=['tenant', 'snapshot_date'], name='ifsnap_tenant_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('router', 'snapshot_date'), name='unique_router_snapshot_date')],
            },
        ),
        migrations.CreateModel(
            name='NetworkArchiveDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_date', models.DateField(db_index=True)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('action_count', models.PositiveIntegerField(default=0)),
                ('ping_count', models.PositiveIntegerField(default=0)),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_days', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_days', to='core.tenant')),
            ],
            options={
                'ordering': ['-archive_date'],
                'indexes': [models.Index(fields=['tenant', 'archive_date'], name='archiveday_tenant_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('router', 'archive_date'), name='unique_router_archive_date')],
            },
        ),
        migrations.CreateModel(
            name='RouterPingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(db_index=True, max_length=255)),
                ('packet_count', models.PositiveSmallIntegerField(default=4)),
                ('received', models.PositiveSmallIntegerField(default=0)),
                ('min_latency_ms', models.FloatField(blank=True, null=True)),
                ('avg_latency_ms', models.FloatField(blank=True, null=True)),
                ('max_latency_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('TIMEOUT', 'Timeout'), ('UNREACHABLE', 'Unreachable'), ('ERROR', 'Error')], db_index=True, default='SUCCESS', max_length=20)),
                ('raw_output', models.JSONField(blank=True, default=list)),
                ('ran_by', models.CharField(blank=True, default='', max_length=150)),
                ('ran_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_results', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_ping_results', to='core.tenant')),
            ],
            options={
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['tenant', 'ran_at'], name='ping_tenant_ranat_idx')],
            },
        ),
    ]
