# Generated by Django 6.1 on 2026-09-26 18:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        ('network', '0020_interfacesnapshot_networkarchiveday_routerpingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireguardconfig',
            name='key_rotation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='last_push_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='last_push_status',
            field=models.CharField(blank=True, default='', help_text='success | failed | pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='last_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='last_pushed_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='last_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='last_rotated_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='wireguardconfig',
            name='mik_public_key_history',
            field=models.JSONField(blank=True, default=list, help_text='Stack of {"fingerprint", "rotated_at", "rotated_by"} records for the most recent MikroTik public keys.'),
        ),
        migrations.CreateModel(
            name='WireGuardAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Configuration created'), ('UPDATED', 'Configuration edited'), ('ROTATED', 'Key rotation'), ('PUSHED', 'Pushed to MikroTik'), ('SUBNET_ADDED', 'Subnet added'), ('SUBNET_REMOVED', 'Subnet removed'), ('DELETED', 'Configuration deleted'), ('HANDSHAKE_FAILED', 'Handshake probe failure')], db_index=True, max_length=30)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=60)),
                ('is_saas_admin', models.BooleanField(default=False, help_text='True when the change came from the SaaS control plane.')),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='network.wireguardconfig')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireguard_audit_events', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireguard_audit_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='wgaudit_tenant_occured_idx'), models.Index(fields=['config', 'occurred_at'], name='wgaudit_config_occurred_idx')],
            },
        ),
        migrations.CreateModel(
            name='WireGuardHandshake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peer_public_key', models.CharField(db_index=True, max_length=128)),
                ('peer_endpoint', models.CharField(blank=True, default='', max_length=128)),
                ('last_handshake_at', models.DateTimeField(blank=True, null=True)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('STALE', 'Stale (no handshake in 2-3 min)'), ('DEAD', 'Dead (no handshake in 5+ min)'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=12)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handshakes', to='network.wireguardconfig')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireguard_handshakes', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireguard_handshakes', to='core.tenant')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['config', 'captured_at'], name='wghs_config_captured_idx')],
            },
        ),
    ]
