# Generated by Django 6.1 on 2026-09-26 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        ('customers', '0006_customer_cpe_admin_password_and_more'),
        ('network', '0021_wireguardconfig_key_rotation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=120)),
                ('usage_date', models.DateField(db_index=True)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('uptime_seconds', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='customers.customer')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core.tenant')),
            ],
            options={
                'ordering': ['-usage_date', '-download_bytes'],
                'indexes': [models.Index(fields=['router', 'usage_date'], name='usagelog_router_date_idx'), models.Index(fields=['customer', 'usage_date'], name='usagelog_customer_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('router', 'username', 'usage_date'), name='usagelog_router_user_date_uniq')],
            },
        ),
    ]
