# Generated by Django 6.1 on 2026-10-05 18:55

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_service_invoice_subscription_and_more'),
        ('core', '0016_notification'),
        ('customers', '0009_customerservice_provisioning_status'),
        ('network', '0022_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppoesecretitem',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pppoesecretitem',
            name='last_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoesecretitem',
            name='password',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pppoesecretitem',
            name='provisioning_status',
            field=models.CharField(choices=[('NOT_PROVISIONED', 'Not Provisioned'), ('PROVISIONING', 'Provisioning'), ('PROVISIONED', 'Provisioned'), ('FAILED', 'Failed'), ('DEPROVISIONING', 'Deprovisioning'), ('DEPROVISIONED', 'Deprovisioned')], db_index=True, default='NOT_PROVISIONED', max_length=30),
        ),
        migrations.AddField(
            model_name='pppoesecretitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pppoe_accounts', to='customers.customerservice'),
        ),
        migrations.AddField(
            model_name='pppoesecretitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='NetworkProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mikrotik_profile', models.CharField(help_text='MikroTik RouterOS / RADIUS Profile name (e.g. 20M, VIP_50M)', max_length=150)),
                ('download_rate_mbps', models.PositiveIntegerField(default=10)),
                ('upload_rate_mbps', models.PositiveIntegerField(default=10)),
                ('burst_download_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_upload_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_threshold_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=8)),
                ('address_pool', models.CharField(blank=True, default='', max_length=100)),
                ('dns_servers', models.CharField(blank=True, default='', max_length=200)),
                ('radius_attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_profiles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pppoesecretitem',
            name='network_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pppoe_accounts', to='network.networkprofile'),
        ),
        migrations.AddIndex(
            model_name='pppoesecretitem',
            index=models.Index(fields=['tenant', 'status'], name='pppoe_tenant_st_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoesecretitem',
            index=models.Index(fields=['tenant', 'provisioning_status'], name='pppoe_tenant_prov_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_network_profile_name'),
        ),
        migrations.AddConstraint(
            model_name='networkprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'mikrotik_profile'), name='unique_tenant_mikrotik_profile_name'),
        ),
    ]
