<?php
// install/install.php

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: ./");
    exit;
}

$host = $_POST['db_host'];
$name = $_POST['db_name'];
$user = $_POST['db_user'];
$pass = $_POST['db_pass'];
$license_key = $_POST['license_key'];
$saas_url = $_POST['saas_url'];
$client_name = trim($_POST['client_name'] ?? '');
$client_dob = trim($_POST['client_date_of_birth'] ?? '');

// Validation
if (empty($client_name)) {
    header("Location: index.php?error=" . urlencode("Please enter Client Name."));
    exit;
}

if (empty($client_dob) || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $client_dob)) {
    header("Location: index.php?error=" . urlencode("Please select a valid Date of Birth."));
    exit;
}

// 1. Verify DB Connection
try {
    $dsn = "mysql:host=$host;charset=utf8";
    $pdo = new PDO($dsn, $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Create DB if not exists
    $pdo->exec("CREATE DATABASE IF NOT EXISTS `$name`");
    $pdo->exec("USE `$name`");
    
} catch (PDOException $e) {
    $error = "Database Connection Failed: " . $e->getMessage();
    header("Location: index.php?error=" . urlencode($error));
    exit;
}

// 2. Write Config File (Tenant vs Main)
$tenant = isset($_POST['tenant']) ? preg_replace('/[^a-zA-Z0-9-]/', '', $_POST['tenant']) : '';

$config_content = "<?php
// Auto-generated by Installer for " . ($tenant ? "Tenant: $tenant" : "Main System") . "
define('DB_HOST', '$host');
define('DB_NAME', '$name');
define('DB_USER', '$user');
define('DB_PASS', '$pass');
?>";

if ($tenant) {
    // Ensure directory exists
    if (!is_dir(__DIR__ . '/../includes/tenants')) {
        mkdir(__DIR__ . '/../includes/tenants', 0755, true);
    }
    $config_file = __DIR__ . '/../includes/tenants/' . $tenant . '.php';
} else {
    $config_file = __DIR__ . '/../includes/db_config.php';
}

if (file_put_contents($config_file, $config_content) === false) {
    header("Location: index.php?error=" . urlencode("Failed to write config file. Check permissions."));
    exit;
}

// 3. Pre-inject License Settings into Database (since we have logic to create tables in config.php)
// We need to wait for config.php to create tables first on next load?
// OR we can include config.php logic here? 
// Simplest is to let config.php handle migration on first load, 
// BUT we need the license key and URL saved.
// So we will perform a "partial boot" or just insert into settings table if we can create it.

try {
    // Create settings table manually here to save license before full boot
    $pdo->exec("CREATE TABLE IF NOT EXISTS settings (id INT AUTO_INCREMENT PRIMARY KEY, key_name VARCHAR(50) UNIQUE, key_value TEXT)");
    
    $stm = $pdo->prepare("INSERT INTO settings (key_name, key_value) VALUES (?, ?) ON DUPLICATE KEY UPDATE key_value=VALUES(key_value)");
    $stm->execute(['saas_license_key', $license_key]);
    $stm->execute(['saas_api_url', $saas_url]);
    $stm->execute(['client_name', $client_name]);
    $stm->execute(['client_date_of_birth', $client_dob]);
    
    // 4. Create Admin Account
    $admin_user = $_POST['admin_username'] ?? 'admin';
    $admin_pass = $_POST['admin_password'] ?? 'admin123';
    
    // Create staff table manually to ensure we can insert admin
    // This schema matches the final schema expected by the app
    $sql_staff = "CREATE TABLE IF NOT EXISTS staff (
        id INT AUTO_INCREMENT PRIMARY KEY, 
        name VARCHAR(100), 
        username VARCHAR(50) UNIQUE, 
        password VARCHAR(50), 
        role VARCHAR(20) DEFAULT 'Reseller', 
        parent_id INT DEFAULT 0, 
        balance DECIMAL(10,2) DEFAULT 0, 
        status VARCHAR(20) DEFAULT 'Active', 
        router_id INT DEFAULT 0, 
        due_balance DECIMAL(10,2) DEFAULT 0, 
        agent_id INT DEFAULT 0, 
        agent_commission DECIMAL(5,2) DEFAULT 0,
        phone VARCHAR(20),
        nid VARCHAR(50),
        address TEXT,
        commission_type ENUM('Fixed', 'Package') DEFAULT 'Fixed',
        sms_config TEXT,
        email VARCHAR(100),
        reset_token VARCHAR(100),
        reset_expiry DATETIME,
        lock_status ENUM('None','Panel','Full') DEFAULT 'None',
        lock_note TEXT DEFAULT NULL
    )";
    $pdo->exec($sql_staff);

    // Insert or Update Admin
    $stm_admin = $pdo->prepare("INSERT INTO staff (username, password, role, name, balance) VALUES (?, ?, 'Admin', 'Super Admin', 0) ON DUPLICATE KEY UPDATE password=?");
    $stm_admin->execute([$admin_user, $admin_pass, $admin_pass]);

} catch (Exception $e) {
    // If this fails, user might need to enter license again, but DB is configured.
    // Proceeding regardless.
}

// 5. Redirect to Main Site
header("Location: ../");
exit;
?>
