# Generated by Django 6.1 on 2026-09-01 13:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('area_zone', models.CharField(blank=True, default='Main Zone', max_length=100)),
                ('connection_type', models.CharField(choices=[('PPPoE', 'PPPoE'), ('Static_IP', 'Static IP'), ('DHCP', 'DHCP / IPoE')], default='PPPoE', max_length=30)),
                ('pppoe_username', models.CharField(db_index=True, max_length=100)),
                ('pppoe_password', models.CharField(max_length=100)),
                ('static_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('onu_mac_or_sn', models.CharField(blank=True, max_length=100)),
                ('billing_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], default='Prepaid', max_length=30)),
                ('monthly_bill', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('promise_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended / Locked'), ('Left', 'Left / Terminated')], db_index=True, default='Active', max_length=30)),
                ('auto_lock_enabled', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='billing.package')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_customers', to='authentication.staffprofile')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'pppoe_username')},
            },
        ),
    ]
