# Generated by Django 6.1 on 2026-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('billing', '0004_alter_invoice_options_and_more'),
        ('core', '0004_companysetting_advance_loan_sms_template_and_more'),
        ('customers', '0001_initial'),
        ('network', '0003_alter_router_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'status'], name='cust_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'expiry_date'], name='cust_tenant_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'created_at'], name='cust_tenant_created_idx'),
        ),
    ]
