# Generated by Django 6.1 on 2026-09-02 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_cust_tenant_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
