# Generated by Django 6.1 on 2026-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_staffprofile_role'),
        ('billing', '0005_package_unique_tenant_package_name'),
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('customers', '0003_alter_customer_bill_date'),
        ('network', '0004_router_api_protocol_router_connection_timeout_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_code', ''), _negated=True), fields=('tenant', 'customer_code'), name='unique_tenant_customer_code'),
        ),
    ]
