# Generated by Django 6.1 on 2026-09-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_unique_tenant_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_password',
            field=models.CharField(blank=True, default='', help_text='Hashed password for self-care portal login', max_length=128),
        ),
    ]
