# Generated by Django 6.1 on 2026-09-26 09:56

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companysetting_funbox_live_tv_api_key_and_more'),
        ('customers', '0005_customer_portal_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cpe_admin_password',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpe_admin_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpe_api_port',
            field=models.IntegerField(default=8728),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpe_api_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpe_management_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpe_pppoe_password',
            field=apps.core.fields.EncryptedCharField(blank=True, help_text='Stored CPE PPPoE password', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpe_router_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PPPoECredentialRescueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('finding', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_events', to='customers.customer')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_rescue_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
