# Generated by Django 6.1 on 2026-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_cpe_admin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='welcome_email_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='welcome_sent_via',
            field=models.CharField(blank=True, default='', help_text='Comma list: sms,email', max_length=32),
        ),
        migrations.AddField(
            model_name='customer',
            name='welcome_sms_log_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='welcome_username',
            field=models.CharField(blank=True, default='', help_text='Username mailed/SMSed to the customer; usually the pppoe_username but overridable.', max_length=128),
        ),
    ]
