# Generated by Django 6.1 on 2026-10-05 18:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_coupon_code_invoice_coupon_discount_and_more'),
        ('core', '0016_notification'),
        ('customers', '0007_welcome_credentials'),
        ('network', '0022_usagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended / Locked'), ('Left', 'Left / Terminated'), ('Archived', 'Archived')], db_index=True, default='Active', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('BROADBAND', 'Broadband Internet'), ('STATIC_IP', 'Dedicated Static IP'), ('IPTV', 'IPTV Service'), ('VOIP', 'VoIP / SIP Trunk'), ('LEASED_LINE', 'Corporate Leased Line')], default='BROADBAND', max_length=30)),
                ('service_identifier', models.CharField(help_text='e.g. PPPoE username, circuit ID, or IP', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='PENDING', max_length=30)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('network_metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_services', to='billing.package')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_services', to='network.router')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_services', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('next_billing_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_subscriptions', to='billing.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customerservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_subscriptions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerservice',
            index=models.Index(fields=['tenant', 'status'], name='svc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customerservice',
            index=models.Index(fields=['customer', 'status'], name='svc_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customerservice',
            index=models.Index(fields=['tenant', 'service_identifier'], name='svc_tenant_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['tenant', 'status'], name='sub_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['customer', 'status'], name='sub_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['service', 'status'], name='sub_svc_status_idx'),
        ),
    ]
