# Generated by Django 6.1 on 2026-10-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_status_customerservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='provisioning_status',
            field=models.CharField(db_index=True, default='NOT_PROVISIONED', help_text='Network hardware provisioning status (NOT_PROVISIONED, PROVISIONING, PROVISIONED, FAILED, DEPROVISIONED)', max_length=30),
        ),
    ]
