# Generated by Django 6.1 on 2026-09-01 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('BKASH', 'bKash Merchant'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket (DBBL)'), ('UPAY', 'Upay'), ('SSLCOMMERZ', 'SSLCommerz'), ('PIPRAPAY', 'PipraPay'), ('SMS_WEBHOOK', 'SMS Automated Hook'), ('MANUAL', 'Cash / Manual Bank')], default='BKASH', max_length=50)),
                ('title', models.CharField(default='bKash Payment', max_length=100)),
                ('merchant_number', models.CharField(blank=True, max_length=50)),
                ('app_key', models.CharField(blank=True, max_length=255)),
                ('app_secret', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trx_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payment_method', models.CharField(default='bKash', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success / Paid'), ('Failed', 'Failed'), ('Matched', 'Matched & Credited'), ('Refunded', 'Refunded')], default='Success', max_length=30)),
                ('customer_account', models.CharField(blank=True, max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentgateway')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=50)),
                ('raw_message', models.TextField()),
                ('parsed_provider', models.CharField(blank=True, max_length=50)),
                ('parsed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parsed_trx_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('parsed_account', models.CharField(blank=True, max_length=50)),
                ('is_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_sms', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
