# Generated by Django 6.1 on 2026-09-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='merchant_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_app_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_app_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='shop_base_url',
            field=models.CharField(blank=True, default='https://shop.bkash.com/merchant', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='shop_payment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='store_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='store_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
