# Generated by Django 6.1 on 2026-09-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentgateway_merchant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='sms_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.smslog'),
        ),
    ]
