# Generated by Django 6.1 on 2026-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysetting_advance_loan_sms_template_and_more'),
        ('customers', '0002_customer_cust_tenant_status_idx_and_more'),
        ('payments', '0003_paymenttransaction_sms_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='tx_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['customer', 'created_at'], name='tx_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'status'], name='tx_tenant_status_idx'),
        ),
    ]
