# Generated by Django 6.1 on 2026-09-07 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenantdomain_auditlog_after_auditlog_before_and_more'),
        ('customers', '0003_alter_customer_bill_date'),
        ('payments', '0004_paymenttransaction_tx_tenant_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundPaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('SMS', 'SMS forwarding'), ('WEBHOOK', 'Provider webhook'), ('MANUAL', 'Manual entry'), ('API', 'API push')], default='SMS', max_length=20)),
                ('raw_payload', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trx_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sender_account', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched (needs review)'), ('DUPLICATE', 'Duplicate (skipped)'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('matched_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='customers.customer')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_event', to='payments.paymenttransaction')),
                ('sms_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='payments.smslog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_payment_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inevent_tenant_status_idx'), models.Index(fields=['tenant', 'trx_id'], name='inevent_tenant_trx_idx'), models.Index(fields=['tenant', 'received_at'], name='inevent_tenant_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('provider', models.CharField(choices=[('BKASH', 'bKash Merchant'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket (DBBL)'), ('UPAY', 'Upay'), ('SSLCOMMERZ', 'SSLCommerz'), ('PIPRAPAY', 'PipraPay'), ('SMS_WEBHOOK', 'SMS Automated Hook'), ('MANUAL', 'Cash / Manual Bank')], default='BKASH', max_length=50)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending confirmation'), ('SUCCESS', 'Confirmed success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('RECONCILED', 'Reconciled')], default='INITIATED', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='customers.customer')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentgateway')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='core.tenant')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='pattempt_tenant_status_idx'), models.Index(fields=['tenant', 'customer', 'initiated_at'], name='pattempt_tenant_cust_ts_idx'), models.Index(fields=['idempotency_key'], name='pattempt_idem_idx')],
            },
        ),
    ]
