# Generated by Django 6.1 on 2026-09-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saaspackage_tenantonboardingrequest_databasebackup_and_more'),
        ('customers', '0004_customer_unique_tenant_customer_code'),
        ('payments', '0005_inboundpaymentevent_paymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundpaymentevent',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='inboundpaymentevent',
            index=models.Index(fields=['tenant', 'reference_id'], name='inevent_tenant_ref_idx'),
        ),
    ]
