# Generated by Django 6.1 on 2026-09-17 06:16

import apps.core.fields
from django.db import migrations


def encrypt_existing_payment_credentials(apps, schema_editor):
    PaymentGateway = apps.get_model('payments', 'PaymentGateway')
    from apps.core.encryption import encrypt_str, is_encrypted

    fields_to_encrypt = [
        'app_key', 'app_secret', 'username', 'password',
        'sandbox_app_key', 'sandbox_app_secret', 'sandbox_username', 'sandbox_password',
        'merchant_number', 'merchant_phone', 'public_key', 'private_key',
        'store_id', 'store_password', 'webhook_secret',
    ]

    for gw in PaymentGateway.objects.all():
        updated = False
        for field_name in fields_to_encrypt:
            val = getattr(gw, field_name, '')
            if val and not is_encrypted(val):
                setattr(gw, field_name, encrypt_str(val))
                updated = True
        if updated:
            gw.save(update_fields=fields_to_encrypt)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_inboundpaymentevent_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='webhook_secret',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='app_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='app_secret',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='merchant_number',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='merchant_phone',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='password',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='private_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='public_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox_app_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox_app_secret',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox_password',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='sandbox_username',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_id',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='store_password',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='username',
            field=apps.core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.RunPython(encrypt_existing_payment_credentials, reverse_code=noop_reverse),
    ]
