# Generated by Django 6.1 on 2026-09-26 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_seed_rbac_catalog'),
        ('customers', '0005_customer_portal_password'),
        ('payments', '0007_encrypt_payment_gateway_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='entity_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RESELLER', 'Reseller'), ('STAFF', 'Staff Wallet')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='initiator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reference_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='authentication.reseller'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='entity_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RESELLER', 'Reseller'), ('STAFF', 'Staff Wallet')], default='CUSTOMER', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='initiator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.reseller'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer'),
        ),
    ]
