# Generated by Django 6.1 on 2026-10-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_service_invoice_subscription_and_more'),
        ('payments', '0008_paymentattempt_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.invoice'),
        ),
    ]
