<?php
// Auto-generated by Installer for Main System
define('DB_HOST', '127.0.0.1;port=3307');
define('DB_NAME', 'shebafi_relationcable');
define('DB_USER', 'shebafi_relationcable');
define('DB_PASS', 'relationcable123@');
?>